package gamecatalog

var games = []Game{
	{
		Key:         "7d2d",
		Aliases:     []string{"7daystodie", "7-days-to-die", "seven_days_to_die", "sevendaystodie"},
		ImageEnv:    "SEVEN_DAYS_TO_DIE_DOCKER_IMAGE",
		Image:       "vortanix/7d2d:latest",
		Name:        "7 Days to Die",
		Description: "7 Days to Die dedicated server.",
		Code:        "7d2d",
		MinPort:     26900,
		MaxPort:     27000,
		PortEnv:     "GAME_PORT",
		Ports:       []PortSpec{{Offset: 0, Protocol: "udp", Purpose: "игровой сервер"}, {Offset: 1, Protocol: "udp", Purpose: "Query"}, {Offset: 2, Protocol: "tcp", Purpose: "Telnet/RCON"}},
		QueryProto:  QueryA2S,
		MinRAMMB:    6144,
		RecRAMMB:    8192,
		MinDiskMB:   16384,
		MinCPU:      2,
		Install:     Install{SourceType: SourceSteam, SteamAppID: 294420, Version: "Steam Default"},
	},
	{
		Key:         "arksa",
		Aliases:     []string{"ark-survival-ascended", "ark_survival_ascended", "ark_ascended", "asa"},
		ImageEnv:    "ARKSA_DOCKER_IMAGE",
		Image:       "vortanix/arksa:latest",
		Name:        "Ark Survival Ascended",
		Description: "ARK: Survival Ascended dedicated server.",
		Code:        "arksa",
		MinPort:     7777,
		MaxPort:     28000,
		PortEnv:     "GAME_PORT",
		Ports:       []PortSpec{{Offset: 0, Protocol: "udp", Purpose: "игровой сервер"}, {Offset: 1, Protocol: "udp", Purpose: "Query"}, {Offset: 10, Protocol: "tcp", Purpose: "RCON"}},
		QueryProto:  QueryA2S,
		MinRAMMB:    16384,
		RecRAMMB:    32768,
		MinDiskMB:   61440,
		MinCPU:      4,
		Install:     Install{SourceType: SourceSteam, SteamAppID: 2430930, Version: "Steam Default"},
	},
	{
		Key:         "arkse",
		Aliases:     []string{"ark-survival-evolved", "ark_survival_evolved", "ark_evolved", "ark"},
		ImageEnv:    "ARKSE_DOCKER_IMAGE",
		Image:       "vortanix/arkse:latest",
		Name:        "ARK: Survival Evolved",
		Description: "ARK: Survival Evolved dedicated server.",
		Code:        "arkse",
		MinPort:     7777,
		MaxPort:     28000,
		PortEnv:     "GAME_PORT",
		Ports:       []PortSpec{{Offset: 0, Protocol: "udp", Purpose: "игровой сервер"}, {Offset: 1, Protocol: "udp", Purpose: "Query"}, {Offset: 10, Protocol: "tcp", Purpose: "RCON"}},
		QueryProto:  QueryA2S,
		MinRAMMB:    8192,
		RecRAMMB:    12288,
		MinDiskMB:   25600,
		MinCPU:      4,
		Install:     Install{SourceType: SourceSteam, SteamAppID: 376030, Version: "Steam Default"},
	},
	{
		Key:         "arma3",
		Aliases:     []string{"arma-3", "arma_3"},
		ImageEnv:    "ARMA3_DOCKER_IMAGE",
		Image:       "vortanix/arma3:latest",
		Name:        "Arma 3",
		Description: "Arma 3 dedicated server.",
		Code:        "arma3",
		MinPort:     2302,
		MaxPort:     2400,
		PortEnv:     "GAME_PORT",
		Ports:       []PortSpec{{Offset: 0, Protocol: "udp", Purpose: "игровой сервер"}, {Offset: 1, Protocol: "udp", Purpose: "Steam query"}, {Offset: 2, Protocol: "udp", Purpose: "VoN"}, {Offset: 3, Protocol: "tcp", Purpose: "RCON"}},
		QueryProto:  QueryA2S,
		MinRAMMB:    4096,
		RecRAMMB:    8192,
		MinDiskMB:   30720,
		MinCPU:      4,
		Install:     Install{SourceType: SourceSteam, SteamAppID: 233780, Version: "Steam Default"},
	},
	{
		Key:         "armaref",
		Aliases:     []string{"arma reforger", "arma-reforger", "arma_reforger"},
		ImageEnv:    "ARMA_REFORGER_DOCKER_IMAGE",
		Image:       "vortanix/armaref:latest",
		Name:        "Arma Reforger",
		Description: "Arma Reforger dedicated server.",
		Code:        "armaref",
		MinPort:     2001,
		MaxPort:     2100,
		PortEnv:     "GAME_PORT",
		Ports:       []PortSpec{{Offset: 0, Protocol: "udp", Purpose: "игровой сервер"}, {Offset: 1, Protocol: "udp", Purpose: "Query"}, {Offset: 10, Protocol: "tcp", Purpose: "RCON"}},
		QueryProto:  QueryA2S,
		MinRAMMB:    8192,
		RecRAMMB:    12288,
		MinDiskMB:   20480,
		MinCPU:      4,
		Install:     Install{SourceType: SourceSteam, SteamAppID: 1874900, Version: "Steam Default"},
	},
	{
		Key:           "bbermuda",
		Aliases:       []string{"beasts of bermuda", "beasts-of-bermuda", "beasts_of_bermuda"},
		ImageEnv:      "BEASTS_OF_BERMUDA_DOCKER_IMAGE",
		Image:         "vortanix/bbermuda:latest",
		Name:          "Beasts of Bermuda",
		Description:   "Beasts of Bermuda dedicated server.",
		Code:          "bbermuda",
		MinPort:       7777,
		MaxPort:       7900,
		PortEnv:       "GAME_PORT",
		Ports:         []PortSpec{{Offset: 0, Protocol: "udp", Purpose: "игровой сервер"}, {Offset: 1, Protocol: "udp", Purpose: "Query"}},
		QueryProto:    QueryA2S,
		MinRAMMB:      6144,
		RecRAMMB:      8192,
		MinDiskMB:     15360,
		MinCPU:        2,
		Install:       Install{SourceType: SourceDocker, Version: "Manual"},
		NoLinuxServer: "в каталоге стоял app клиентской игры; все её депоты windows, отдельного линуксового серверного приложения в Steam нет",
	},
	{
		Key:         "conan",
		Aliases:     []string{"conan exiles", "conan-exiles", "conan_exiles"},
		ImageEnv:    "CONAN_EXILES_DOCKER_IMAGE",
		Image:       "vortanix/conan:latest",
		Name:        "Conan Exiles",
		Description: "Conan Exiles dedicated server.",
		Code:        "conan",
		MinPort:     7777,
		MaxPort:     7900,
		PortEnv:     "GAME_PORT",
		Ports:       []PortSpec{{Offset: 0, Protocol: "udp", Purpose: "игровой сервер"}, {Offset: 1, Protocol: "udp", Purpose: "Query"}, {Offset: 10, Protocol: "tcp", Purpose: "RCON"}},
		QueryProto:  QueryA2S,
		MinRAMMB:    8192,
		RecRAMMB:    12288,
		MinDiskMB:   40960,
		MinCPU:      4,
		Install:     Install{SourceType: SourceSteam, SteamAppID: 443030, Version: "Steam Default"},
	},
	{
		Key:         "crmp",
		Aliases:     []string{"gta_crmp", "cr-mp", "cr-mp0.3"},
		ImageEnv:    "CRMP_DOCKER_IMAGE",
		Image:       "vortanix/crmp:latest",
		Name:        "CRMP",
		Description: "CRMP server (based on SA-MP).",
		Code:        "crmp",
		MinPort:     7777,
		MaxPort:     7877,
		PortEnv:     "CRMP_PORT",
		Ports:       []PortSpec{{Offset: 0, Protocol: "udp", Purpose: "игровой сервер"}},
		QueryProto:  QuerySAMP,
		MinRAMMB:    128,
		RecRAMMB:    256,
		MinDiskMB:   1024,
		MinCPU:      0.5,
		Install:     Install{SourceType: SourceDocker, Version: "manual", Note: "CRMP распространяется только сборками сообщества: официальной ссылки на samp03svr-cr нет"},
	},
	{
		Key:         "cs16",
		Aliases:     []string{"cstrike", "counter-strike", "counter_strike", "cs_1_6"},
		ImageEnv:    "CS16_DOCKER_IMAGE",
		Image:       "vortanix/cs16:latest",
		Name:        "Counter-Strike 1.6",
		Description: "Classic Counter-Strike 1.6 multiplayer server",
		Code:        "cstrike",
		MinPort:     27015,
		MaxPort:     27030,
		PortEnv:     "CS16_PORT",
		Ports:       []PortSpec{{Offset: 0, Protocol: "udp", Purpose: "игровой сервер"}, {Offset: 0, Protocol: "tcp", Purpose: "RCON"}},
		QueryProto:  QueryA2S,
		MaxSlots:    32,
		MinRAMMB:    256,
		RecRAMMB:    512,
		MinDiskMB:   2048,
		MinCPU:      0.5,
		Install:     Install{SourceType: SourceSteam, SteamAppID: 90, SteamModConfig: "cstrike", Version: "Steam Default"},
	},
	{
		Key:         "cs2",
		Aliases:     []string{"counter-strike2", "counter_strike2", "counter-strike_2", "counter_strike_2", "counter-strike 2"},
		ImageEnv:    "CS2_DOCKER_IMAGE",
		Image:       "vortanix/cs2:latest",
		Name:        "Counter-Strike 2",
		Description: "Counter-Strike 2 dedicated server.",
		Code:        "cs2",
		MinPort:     27015,
		MaxPort:     27030,
		PortEnv:     "CS2_PORT",
		Ports:       []PortSpec{{Offset: 0, Protocol: "udp", Purpose: "игровой сервер"}, {Offset: 0, Protocol: "tcp", Purpose: "RCON"}},
		QueryProto:  QueryA2S,
		MaxSlots:    64,
		MinRAMMB:    2048,
		RecRAMMB:    3072,
		MinDiskMB:   35840,
		MinCPU:      2,
		Install:     Install{SourceType: SourceSteam, SteamAppID: 740, Version: "Steam Default"},
	},
	{
		Key:         "css",
		Aliases:     []string{"cs:s", "cs_source", "counter-strike_source", "counter_strike_source", "counter-strike source", "counter_strike source"},
		ImageEnv:    "CSS_DOCKER_IMAGE",
		Image:       "vortanix/css:latest",
		Name:        "Counter-Strike: Source",
		Description: "Counter-Strike: Source dedicated server.",
		Code:        "css",
		MinPort:     27015,
		MaxPort:     27030,
		PortEnv:     "CSS_PORT",
		Ports:       []PortSpec{{Offset: 0, Protocol: "udp", Purpose: "игровой сервер"}, {Offset: 0, Protocol: "tcp", Purpose: "RCON"}},
		QueryProto:  QueryA2S,
		MaxSlots:    64,
		MinRAMMB:    768,
		RecRAMMB:    1024,
		MinDiskMB:   12288,
		MinCPU:      1,
		Install:     Install{SourceType: SourceSteam, SteamAppID: 232330, Version: "Steam Default"},
	},
	{
		Key:           "daydrag",
		Aliases:       []string{"day of dragons", "day-of-dragons", "day_of_dragons"},
		ImageEnv:      "DAY_OF_DRAGONS_DOCKER_IMAGE",
		Image:         "vortanix/daydrag:latest",
		Name:          "Day of Dragons",
		Description:   "Day of Dragons dedicated server.",
		Code:          "daydrag",
		MinPort:       7777,
		MaxPort:       7900,
		PortEnv:       "GAME_PORT",
		Ports:         []PortSpec{{Offset: 0, Protocol: "udp", Purpose: "игровой сервер"}, {Offset: 1, Protocol: "udp", Purpose: "Query"}},
		QueryProto:    QueryA2S,
		MinRAMMB:      6144,
		RecRAMMB:      8192,
		MinDiskMB:     10240,
		MinCPU:        2,
		Install:       Install{SourceType: SourceDocker, Version: "Manual"},
		NoLinuxServer: "в каталоге стоял app клиентской игры; все её депоты windows, линуксового серверного приложения в Steam нет",
	},
	{
		Key:         "dayz",
		Aliases:     []string{"dayz-standalone", "dayz_standalone"},
		ImageEnv:    "DAYZ_DOCKER_IMAGE",
		Image:       "vortanix/dayz:latest",
		Name:        "DayZ Standalone",
		Description: "DayZ Standalone dedicated server.",
		Code:        "dayz",
		MinPort:     2302,
		MaxPort:     2400,
		PortEnv:     "GAME_PORT",
		Ports:       []PortSpec{{Offset: 0, Protocol: "udp", Purpose: "игровой сервер"}, {Offset: 1, Protocol: "udp", Purpose: "Steam query"}, {Offset: 10, Protocol: "tcp", Purpose: "RCON"}},
		QueryProto:  QueryA2S,
		MinRAMMB:    6144,
		RecRAMMB:    8192,
		MinDiskMB:   20480,
		MinCPU:      4,
		Install:     Install{SourceType: SourceSteam, SteamAppID: 223350, Version: "Steam Default"},
	},
	{
		Key:         "dayzdev",
		Aliases:     []string{"dayz standalone dev", "dayz-standalone-dev", "dayz_standalone_dev", "dayz experimental"},
		ImageEnv:    "DAYZ_DEV_DOCKER_IMAGE",
		Image:       "vortanix/dayzdev:latest",
		Name:        "DayZ Standalone DEV",
		Description: "DayZ Standalone DEV dedicated server.",
		Code:        "dayzdev",
		MinPort:     2302,
		MaxPort:     2400,
		PortEnv:     "GAME_PORT",
		Ports:       []PortSpec{{Offset: 0, Protocol: "udp", Purpose: "игровой сервер"}, {Offset: 1, Protocol: "udp", Purpose: "Steam query"}, {Offset: 10, Protocol: "tcp", Purpose: "RCON"}},
		QueryProto:  QueryA2S,
		MinRAMMB:    6144,
		RecRAMMB:    8192,
		MinDiskMB:   20480,
		MinCPU:      4,
		Install:     Install{SourceType: SourceSteam, SteamAppID: 223350, SteamBranch: "experimental", Version: "Steam Experimental"},
	},
	{
		Key:           "draconia",
		Aliases:       []string{"draconia-online"},
		ImageEnv:      "DRACONIA_DOCKER_IMAGE",
		Image:         "vortanix/draconia:latest",
		Name:          "Draconia",
		Description:   "Draconia dedicated server.",
		Code:          "draconia",
		MinPort:       27015,
		MaxPort:       27100,
		PortEnv:       "GAME_PORT",
		Ports:         []PortSpec{{Offset: 0, Protocol: "udp", Purpose: "игровой сервер"}, {Offset: 1, Protocol: "udp", Purpose: "Query"}},
		QueryProto:    QueryA2S,
		MinRAMMB:      6144,
		RecRAMMB:      8192,
		MinDiskMB:     10240,
		MinCPU:        2,
		Install:       Install{SourceType: SourceDocker, Version: "Manual"},
		NoLinuxServer: "app 1299430 — это другая игра, «Extortion»; у самой Draconia (1295900) отдельного серверного приложения в Steam нет",
	},
	{
		Key:         "empyrion",
		Aliases:     []string{"empyrion galactic survival", "empyrion-galactic-survival", "empyrion_galactic_survival"},
		ImageEnv:    "EMPYRION_DOCKER_IMAGE",
		Image:       "vortanix/empyrion:latest",
		Name:        "Empyrion - Galactic Survival",
		Description: "Empyrion dedicated server.",
		Code:        "empyrion",
		MinPort:     30000,
		MaxPort:     30100,
		PortEnv:     "GAME_PORT",
		Ports:       []PortSpec{{Offset: 0, Protocol: "udp", Purpose: "игровой сервер"}, {Offset: 1, Protocol: "udp", Purpose: "Steam query"}, {Offset: 10, Protocol: "tcp", Purpose: "Telnet"}},
		QueryProto:  QueryA2S,
		MinRAMMB:    6144,
		RecRAMMB:    8192,
		MinDiskMB:   15360,
		MinCPU:      2,
		Install:     Install{SourceType: SourceSteam, SteamAppID: 530870, Version: "Steam Default"},
	},
	{
		Key:         "enshroud",
		Aliases:     []string{"enshrouded", "enshrouded-server"},
		ImageEnv:    "ENSHROUDED_DOCKER_IMAGE",
		Image:       "vortanix/enshroud:latest",
		Name:        "Enshrouded",
		Description: "Enshrouded dedicated server.",
		Code:        "enshroud",
		MinPort:     15637,
		MaxPort:     15700,
		PortEnv:     "GAME_PORT",
		Ports:       []PortSpec{{Offset: 0, Protocol: "udp", Purpose: "игровой сервер"}, {Offset: 1, Protocol: "udp", Purpose: "Query"}},
		QueryProto:  QueryA2S,
		MinRAMMB:    10240,
		RecRAMMB:    16384,
		MinDiskMB:   20480,
		MinCPU:      4,
		Install:     Install{SourceType: SourceSteam, SteamAppID: 2278520, Version: "Steam Default"},
	},
	{
		Key:         "factorio",
		Aliases:     []string{"factorio-server"},
		ImageEnv:    "FACTORIO_DOCKER_IMAGE",
		Image:       "vortanix/factorio:latest",
		Name:        "Factorio",
		Description: "Factorio dedicated server.",
		Code:        "factorio",
		MinPort:     34197,
		MaxPort:     34220,
		PortEnv:     "GAME_PORT",
		Ports:       []PortSpec{{Offset: 0, Protocol: "udp", Purpose: "игровой сервер"}, {Offset: 10, Protocol: "tcp", Purpose: "RCON"}},
		QueryProto:  QueryNone,
		MinRAMMB:    512,
		RecRAMMB:    1024,
		MinDiskMB:   2048,
		MinCPU:      1,
		Install:     Install{SourceType: SourceDocker, Version: "manual", Note: "анонимный SteamCMD app 427520 не отдаёт, а headless-сборка с factorio.com — .tar.xz, который агент не распаковывает: файлы заливает админ"},
	},
	{
		Key:         "gmod",
		Aliases:     []string{"garrysmod", "garry's mod", "garrys_mod"},
		ImageEnv:    "GMOD_DOCKER_IMAGE",
		Image:       "vortanix/gmod:latest",
		Name:        "Garry's Mod",
		Description: "Garry's Mod dedicated server (Source)",
		Code:        "gmod",
		MinPort:     27015,
		MaxPort:     27060,
		PortEnv:     "GMOD_PORT",
		Ports:       []PortSpec{{Offset: 0, Protocol: "udp", Purpose: "игровой сервер"}, {Offset: 0, Protocol: "tcp", Purpose: "RCON"}},
		QueryProto:  QueryA2S,
		MaxSlots:    128,
		MinRAMMB:    1024,
		RecRAMMB:    2048,
		MinDiskMB:   12288,
		MinCPU:      1,
		Install:     Install{SourceType: SourceSteam, SteamAppID: 4020, Version: "Steam Default"},
	},
	{
		Key:         "hytale",
		Aliases:     []string{"hytale-server"},
		ImageEnv:    "HYTALE_DOCKER_IMAGE",
		Image:       "vortanix/hytale:latest",
		Name:        "Hytale",
		Description: "Hytale server profile.",
		Code:        "hytale",
		MinPort:     25565,
		MaxPort:     25650,
		PortEnv:     "GAME_PORT",
		Ports:       []PortSpec{{Offset: 0, Protocol: "tcp", Purpose: "игровой сервер"}},
		QueryProto:  QueryNone,
		MinRAMMB:    4096,
		RecRAMMB:    6144,
		MinDiskMB:   8192,
		MinCPU:      2,
		Install:     Install{SourceType: SourceDocker, Version: "manual", Note: "публичного выделенного сервера Hytale нет; App ID 2140520 из старой панели не проверен"},
	},
	{
		Key:         "icarus",
		Aliases:     []string{"icarus server", "icarus-survival"},
		ImageEnv:    "ICARUS_DOCKER_IMAGE",
		Image:       "vortanix/icarus:latest",
		Name:        "Icarus",
		Description: "Icarus dedicated server.",
		Code:        "icarus",
		MinPort:     17777,
		MaxPort:     17850,
		PortEnv:     "GAME_PORT",
		Ports:       []PortSpec{{Offset: 0, Protocol: "udp", Purpose: "игровой сервер"}, {Offset: 1, Protocol: "udp", Purpose: "Query"}},
		QueryProto:  QueryA2S,
		MinRAMMB:    8192,
		RecRAMMB:    12288,
		MinDiskMB:   25600,
		MinCPU:      4,
		Install:     Install{SourceType: SourceSteam, SteamAppID: 2089300, Version: "Steam Default"},
	},
	{
		Key:         "isleevr",
		Aliases:     []string{"the isle evrima", "the-isle-evrima", "the_isle_evrima", "evrima"},
		ImageEnv:    "THE_ISLE_EVRIMA_DOCKER_IMAGE",
		Image:       "vortanix/isleevr:latest",
		Name:        "The Isle EVRIMA",
		Description: "The Isle EVRIMA dedicated server.",
		Code:        "isleevr",
		MinPort:     7777,
		MaxPort:     7900,
		PortEnv:     "GAME_PORT",
		Ports:       []PortSpec{{Offset: 0, Protocol: "udp", Purpose: "игровой сервер"}, {Offset: 1, Protocol: "udp", Purpose: "Steam query"}},
		QueryProto:  QueryA2S,
		MinRAMMB:    8192,
		RecRAMMB:    12288,
		MinDiskMB:   20480,
		MinCPU:      4,
		Install:     Install{SourceType: SourceSteam, SteamAppID: 412680, SteamBranch: "evrima", Version: "Steam EVRIMA"},
	},
	{
		Key:           "lifeyo",
		Aliases:       []string{"life is feudal your own", "life-is-feudal-your-own", "life_is_feudal_your_own"},
		ImageEnv:      "LIFE_IS_FEUDAL_DOCKER_IMAGE",
		Image:         "vortanix/lifeyo:latest",
		Name:          "Life is Feudal: Your Own",
		Description:   "Life is Feudal: Your Own dedicated server.",
		Code:          "lifeyo",
		MinPort:       28000,
		MaxPort:       28100,
		PortEnv:       "GAME_PORT",
		Ports:         []PortSpec{{Offset: 0, Protocol: "udp", Purpose: "игровой сервер"}, {Offset: 10, Protocol: "tcp", Purpose: "RCON"}},
		QueryProto:    QueryA2S,
		MinRAMMB:      4096,
		RecRAMMB:      6144,
		MinDiskMB:     10240,
		MinCPU:        2,
		Install:       Install{SourceType: SourceDocker, Version: "Manual"},
		NoLinuxServer: "в каталоге стоял app клиентской игры; все её депоты windows, линуксового серверного приложения в Steam нет",
	},
	{
		Key:         "mcbedrock",
		Aliases:     []string{"mcbedrk", "bedrock"},
		ImageEnv:    "MC_BEDROCK_DOCKER_IMAGE",
		Image:       "vortanix/mcbedrock:latest",
		Name:        "Minecraft Bedrock",
		Description: "Minecraft Bedrock Edition server",
		Code:        "bedrock",
		MinPort:     19132,
		MaxPort:     19160,
		PortEnv:     "SERVER_PORT",
		Ports:       []PortSpec{{Offset: 0, Protocol: "udp", Purpose: "основной сервер"}, {Offset: 1, Protocol: "udp", Purpose: "IPv6"}},
		QueryProto:  QueryMC,
		MinRAMMB:    512,
		RecRAMMB:    1024,
		MinDiskMB:   1024,
		MinCPU:      1,
		Install:     Install{SourceType: SourceDocker, Version: "latest", Note: "образ сам качает bedrock-server.zip с minecraft.net при первом запуске"},
	},
	{
		Key:         "mcjava",
		Aliases:     []string{"minecraft"},
		ImageEnv:    "MC_JAVA_DOCKER_IMAGE",
		Image:       "vortanix/mcjava:latest",
		Name:        "Minecraft Java (Vanilla)",
		Description: "Minecraft Java Edition (Vanilla) server",
		Code:        "mcjava",
		MinPort:     25565,
		MaxPort:     25600,
		PortEnv:     "SERVER_PORT",
		Ports:       []PortSpec{{Offset: 0, Protocol: "tcp", Purpose: "игровой сервер"}, {Offset: 0, Protocol: "udp", Purpose: "Query"}, {Offset: 10, Protocol: "tcp", Purpose: "RCON"}},
		QueryProto:  QueryMC,
		MinRAMMB:    1024,
		RecRAMMB:    2048,
		MinDiskMB:   2048,
		MinCPU:      1,
		Install:     Install{SourceType: SourceArchive, ArchiveURL: "https://piston-data.mojang.com/v1/objects/823e2250d24b3ddac457a60c92a6a941943fcd6a/server.jar", Version: "26.2"},
	},
	{
		Key:         "mcpaper",
		Aliases:     nil,
		ImageEnv:    "MC_JAVA_DOCKER_IMAGE",
		Image:       "vortanix/mcjava:latest",
		Name:        "Minecraft Java (Paper)",
		Description: "Minecraft Java Edition (Paper) server",
		Code:        "mcpaper",
		MinPort:     25565,
		MaxPort:     25600,
		PortEnv:     "SERVER_PORT",
		Ports:       []PortSpec{{Offset: 0, Protocol: "tcp", Purpose: "игровой сервер"}, {Offset: 0, Protocol: "udp", Purpose: "Query"}, {Offset: 10, Protocol: "tcp", Purpose: "RCON"}},
		QueryProto:  QueryMC,
		MinRAMMB:    1024,
		RecRAMMB:    2048,
		MinDiskMB:   2048,
		MinCPU:      1,
		Install:     Install{SourceType: SourceArchive, ArchiveURL: "https://fill-data.papermc.io/v1/objects/bd3a58cf96874e5ea6643f5f6fe9b4f5bf9e34b795fa078c2f0ee8b98b2f907e/paper-26.2-112.jar", Version: "26.2-112"},
	},
	{
		Key:         "mcspigot",
		Aliases:     nil,
		ImageEnv:    "MC_JAVA_DOCKER_IMAGE",
		Image:       "vortanix/mcjava:latest",
		Name:        "Minecraft Java (Spigot)",
		Description: "Minecraft Java Edition (Spigot) server",
		Code:        "mcspigot",
		MinPort:     25565,
		MaxPort:     25600,
		PortEnv:     "SERVER_PORT",
		Ports:       []PortSpec{{Offset: 0, Protocol: "tcp", Purpose: "игровой сервер"}, {Offset: 0, Protocol: "udp", Purpose: "Query"}, {Offset: 10, Protocol: "tcp", Purpose: "RCON"}},
		QueryProto:  QueryMC,
		MinRAMMB:    1024,
		RecRAMMB:    2048,
		MinDiskMB:   2048,
		MinCPU:      1,
		Install:     Install{SourceType: SourceDocker, Version: "manual", Note: "Spigot нельзя раздавать готовым jar по лицензии: сервер собирается BuildTools"},
	},
	{
		Key:         "mcforge",
		Aliases:     nil,
		ImageEnv:    "MC_JAVA_DOCKER_IMAGE",
		Image:       "vortanix/mcjava:latest",
		Name:        "Minecraft Java (Forge)",
		Description: "Minecraft Java Edition (Forge) server",
		Code:        "mcforge",
		MinPort:     25565,
		MaxPort:     25600,
		PortEnv:     "SERVER_PORT",
		Ports:       []PortSpec{{Offset: 0, Protocol: "tcp", Purpose: "игровой сервер"}, {Offset: 0, Protocol: "udp", Purpose: "Query"}, {Offset: 10, Protocol: "tcp", Purpose: "RCON"}},
		QueryProto:  QueryMC,
		MinRAMMB:    2048,
		RecRAMMB:    3072,
		MinDiskMB:   4096,
		MinCPU:      1,
		Install:     Install{SourceType: SourceDocker, Version: "manual", Note: "Forge раздаёт installer, а не готовый server.jar: установку выполняет админ"},
	},
	{
		Key:         "mcfabric",
		Aliases:     nil,
		ImageEnv:    "MC_JAVA_DOCKER_IMAGE",
		Image:       "vortanix/mcjava:latest",
		Name:        "Minecraft Java (Fabric)",
		Description: "Minecraft Java Edition (Fabric) server",
		Code:        "mcfabric",
		MinPort:     25565,
		MaxPort:     25600,
		PortEnv:     "SERVER_PORT",
		Ports:       []PortSpec{{Offset: 0, Protocol: "tcp", Purpose: "игровой сервер"}, {Offset: 0, Protocol: "udp", Purpose: "Query"}, {Offset: 10, Protocol: "tcp", Purpose: "RCON"}},
		QueryProto:  QueryMC,
		MinRAMMB:    1536,
		RecRAMMB:    2560,
		MinDiskMB:   3072,
		MinCPU:      1,
		Install:     Install{SourceType: SourceArchive, ArchiveURL: "https://meta.fabricmc.net/v2/versions/loader/26.2/0.19.3/1.1.2/server/jar", Version: "26.2 (Fabric 0.19.3)"},
	},
	{
		Key:         "mordhau",
		Aliases:     []string{"mordhau server"},
		ImageEnv:    "MORDHAU_DOCKER_IMAGE",
		Image:       "vortanix/mordhau:latest",
		Name:        "Mordhau",
		Description: "Mordhau dedicated server.",
		Code:        "mordhau",
		MinPort:     7777,
		MaxPort:     7900,
		PortEnv:     "GAME_PORT",
		Ports:       []PortSpec{{Offset: 0, Protocol: "udp", Purpose: "игровой сервер"}, {Offset: 1, Protocol: "udp", Purpose: "Query"}, {Offset: 10, Protocol: "tcp", Purpose: "RCON"}},
		QueryProto:  QueryA2S,
		MinRAMMB:    4096,
		RecRAMMB:    6144,
		MinDiskMB:   15360,
		MinCPU:      2,
		Install:     Install{SourceType: SourceSteam, SteamAppID: 629800, Version: "Steam Default"},
	},
	{
		Key:         "mta",
		Aliases:     []string{"mtasa", "mta-sa", "mta_sa"},
		ImageEnv:    "MTA_DOCKER_IMAGE",
		Image:       "vortanix/mta:latest",
		Name:        "MTA:SA",
		Description: "Multi Theft Auto: San Andreas dedicated server.",
		Code:        "mta",
		MinPort:     22003,
		MaxPort:     22100,
		PortEnv:     "MTA_PORT",
		Ports:       []PortSpec{{Offset: 0, Protocol: "udp", Purpose: "игровой сервер"}, {Offset: 2, Protocol: "tcp", Purpose: "HTTP сервер"}, {Offset: 123, Protocol: "udp", Purpose: "дополнительный порт"}},
		QueryProto:  QueryNone,
		MinRAMMB:    256,
		RecRAMMB:    512,
		MinDiskMB:   1024,
		MinCPU:      0.5,
		Install:     Install{SourceType: SourceArchive, ArchiveURL: "https://linux.mtasa.com/dl/multitheftauto_linux_x64.tar.gz", Version: "1.6 x64"},
	},
	{
		Key:           "nosurv",
		Aliases:       []string{"no one survived", "no-one-survived", "no_one_survived"},
		ImageEnv:      "NO_ONE_SURVIVED_DOCKER_IMAGE",
		Image:         "vortanix/nosurv:latest",
		Name:          "No One Survived",
		Description:   "No One Survived dedicated server.",
		Code:          "nosurv",
		MinPort:       7777,
		MaxPort:       7900,
		PortEnv:       "GAME_PORT",
		Ports:         []PortSpec{{Offset: 0, Protocol: "udp", Purpose: "игровой сервер"}, {Offset: 1, Protocol: "udp", Purpose: "Query"}},
		QueryProto:    QueryA2S,
		MinRAMMB:      6144,
		RecRAMMB:      8192,
		MinDiskMB:     12288,
		MinCPU:        2,
		Install:       Install{SourceType: SourceDocker, Version: "Manual"},
		NoLinuxServer: "в каталоге стоял app клиентской игры; линуксового серверного приложения в Steam нет",
	},
	{
		Key:         "palworld",
		Aliases:     []string{"pal-world"},
		ImageEnv:    "PALWORLD_DOCKER_IMAGE",
		Image:       "vortanix/palworld:latest",
		Name:        "Palworld",
		Description: "Palworld dedicated server.",
		Code:        "palworld",
		MinPort:     8211,
		MaxPort:     8250,
		PortEnv:     "GAME_PORT",
		Ports:       []PortSpec{{Offset: 0, Protocol: "udp", Purpose: "игровой сервер"}, {Offset: 1, Protocol: "udp", Purpose: "Query"}, {Offset: 10, Protocol: "tcp", Purpose: "RCON"}},
		QueryProto:  QueryA2S,
		MaxSlots:    32,
		MinRAMMB:    8192,
		RecRAMMB:    16384,
		MinDiskMB:   8192,
		MinCPU:      4,
		Install:     Install{SourceType: SourceSteam, SteamAppID: 2394010, Version: "Steam Default"},
	},
	{
		Key:           "pathtit",
		Aliases:       []string{"path of titans", "path-of-titans", "path_of_titans"},
		ImageEnv:      "PATH_OF_TITANS_DOCKER_IMAGE",
		Image:         "vortanix/pathtit:latest",
		Name:          "Path of Titans",
		Description:   "Path of Titans dedicated server.",
		Code:          "pathtit",
		MinPort:       7777,
		MaxPort:       7900,
		PortEnv:       "GAME_PORT",
		Ports:         []PortSpec{{Offset: 0, Protocol: "udp", Purpose: "игровой сервер"}, {Offset: 1, Protocol: "udp", Purpose: "Query"}},
		QueryProto:    QueryA2S,
		MinRAMMB:      6144,
		RecRAMMB:      8192,
		MinDiskMB:     10240,
		MinCPU:        2,
		Install:       Install{SourceType: SourceDocker, Version: "Manual"},
		NoLinuxServer: "app 700000 в Steam не существует: сервер Path of Titans раздаёт Alderon Games собственным загрузчиком, а не через SteamCMD",
	},
	{
		Key:         "pzomboid",
		Aliases:     []string{"project-zomboid", "project_zomboid", "zomboid"},
		ImageEnv:    "PROJECT_ZOMBOID_DOCKER_IMAGE",
		Image:       "vortanix/pzomboid:latest",
		Name:        "Project Zomboid",
		Description: "Project Zomboid dedicated server.",
		Code:        "pzomboid",
		MinPort:     16261,
		MaxPort:     16300,
		PortEnv:     "GAME_PORT",
		Ports:       []PortSpec{{Offset: 0, Protocol: "udp", Purpose: "игровой сервер"}, {Offset: 1, Protocol: "udp", Purpose: "Steam query"}, {Offset: 10, Protocol: "tcp", Purpose: "RCON"}},
		QueryProto:  QueryA2S,
		MinRAMMB:    2048,
		RecRAMMB:    3072,
		MinDiskMB:   5120,
		MinCPU:      2,
		Install:     Install{SourceType: SourceSteam, SteamAppID: 380870, Version: "Steam Default"},
	},
	{
		Key:           "rs2vn",
		Aliases:       []string{"rising storm 2 vietnam", "rising-storm-2-vietnam", "rising_storm_2_vietnam"},
		ImageEnv:      "RS2_VIETNAM_DOCKER_IMAGE",
		Image:         "vortanix/rs2vn:latest",
		Name:          "Rising Storm 2 Vietnam",
		Description:   "Rising Storm 2 Vietnam dedicated server.",
		Code:          "rs2vn",
		MinPort:       7777,
		MaxPort:       7900,
		PortEnv:       "GAME_PORT",
		Ports:         []PortSpec{{Offset: 0, Protocol: "udp", Purpose: "игровой сервер"}, {Offset: 1, Protocol: "udp", Purpose: "Query"}, {Offset: 10, Protocol: "tcp", Purpose: "WebAdmin/RCON"}},
		QueryProto:    QueryA2S,
		MinRAMMB:      4096,
		RecRAMMB:      6144,
		MinDiskMB:     30720,
		MinCPU:        2,
		Install:       Install{SourceType: SourceDocker, Version: "Manual"},
		NoLinuxServer: "серверное приложение — 418480 «Rising Storm 2 - Dedicated Server», oslist windows; линуксовой сборки сервера нет",
	},
	{
		Key:         "rust",
		Aliases:     nil,
		ImageEnv:    "RUST_DOCKER_IMAGE",
		Image:       "vortanix/rust:latest",
		Name:        "Rust",
		Description: "Rust dedicated server.",
		Code:        "rust",
		MinPort:     28015,
		MaxPort:     28100,
		PortEnv:     "RUST_PORT",
		Ports:       []PortSpec{{Offset: 0, Protocol: "udp", Purpose: "игровой сервер"}, {Offset: 1, Protocol: "udp", Purpose: "Query"}, {Offset: 1, Protocol: "tcp", Purpose: "RCON"}},
		QueryProto:  QueryA2S,
		MinRAMMB:    8192,
		RecRAMMB:    16384,
		MinDiskMB:   20480,
		MinCPU:      4,
		Install:     Install{SourceType: SourceSteam, SteamAppID: 258550, Version: "Steam Default"},
	},
	{
		Key:         "samp",
		Aliases:     []string{"sa-mp", "samp03", "gta_samp"},
		ImageEnv:    "SAMP_DOCKER_IMAGE",
		Image:       "vortanix/samp:0.3.7-r3",
		Name:        "SA-MP",
		Description: "San Andreas Multiplayer dedicated server.",
		Code:        "samp",
		MinPort:     7777,
		MaxPort:     7877,
		PortEnv:     "SAMP_PORT",
		Ports:       []PortSpec{{Offset: 0, Protocol: "udp", Purpose: "игровой сервер"}},
		QueryProto:  QuerySAMP,
		MaxSlots:    1000,
		MinRAMMB:    128,
		RecRAMMB:    256,
		MinDiskMB:   512,
		MinCPU:      0.5,
		Install: Install{
			SourceType: SourceArchive,
			Version:    "0.3.7-R2-1",
			ArchiveURL: "https://gta-multiplayer.cz/downloads/samp037svr_R2-2-1.tar.gz",
		},
	},
	{
		Key:         "satisfac",
		Aliases:     []string{"satisfactory", "satisfactory-server"},
		ImageEnv:    "SATISFACTORY_DOCKER_IMAGE",
		Image:       "vortanix/satisfac:latest",
		Name:        "Satisfactory",
		Description: "Satisfactory dedicated server.",
		Code:        "satisfac",
		MinPort:     7777,
		MaxPort:     7900,
		PortEnv:     "GAME_PORT",
		Ports:       []PortSpec{{Offset: 0, Protocol: "udp", Purpose: "игровой сервер"}, {Offset: 1, Protocol: "udp", Purpose: "Query"}},
		QueryProto:  QueryA2S,
		MinRAMMB:    6144,
		RecRAMMB:    12288,
		MinDiskMB:   15360,
		MinCPU:      4,
		Install:     Install{SourceType: SourceSteam, SteamAppID: 1690800, Version: "Steam Default"},
	},
	{
		Key:           "scum",
		Aliases:       []string{"scum server"},
		ImageEnv:      "SCUM_DOCKER_IMAGE",
		Image:         "vortanix/scum:latest",
		Name:          "SCUM",
		Description:   "SCUM dedicated server.",
		Code:          "scum",
		MinPort:       7777,
		MaxPort:       7900,
		PortEnv:       "GAME_PORT",
		Ports:         []PortSpec{{Offset: 0, Protocol: "udp", Purpose: "игровой сервер"}, {Offset: 1, Protocol: "udp", Purpose: "Query"}, {Offset: 10, Protocol: "tcp", Purpose: "RCON"}},
		QueryProto:    QueryA2S,
		MinRAMMB:      10240,
		RecRAMMB:      16384,
		MinDiskMB:     30720,
		MinCPU:        4,
		Install:       Install{SourceType: SourceDocker, Version: "Manual"},
		NoLinuxServer: "серверное приложение SCUM — 3792580, но его контентный депот только под Windows; линуксовых серверных файлов у издателя нет",
	},
	{
		Key:         "sotf",
		Aliases:     []string{"sons of the forest", "sons-of-the-forest", "sons_of_the_forest"},
		ImageEnv:    "SOTF_DOCKER_IMAGE",
		Image:       "vortanix/sotf:latest",
		Name:        "Sons Of The Forest",
		Description: "Sons Of The Forest dedicated server.",
		Code:        "sotf",
		MinPort:     8766,
		MaxPort:     8850,
		PortEnv:     "GAME_PORT",
		Ports:       []PortSpec{{Offset: 0, Protocol: "udp", Purpose: "игровой сервер"}, {Offset: 1, Protocol: "udp", Purpose: "Query"}},
		QueryProto:  QueryA2S,
		MinRAMMB:    6144,
		RecRAMMB:    8192,
		MinDiskMB:   10240,
		MinCPU:      2,
		Install:     Install{SourceType: SourceSteam, SteamAppID: 2465200, Version: "Steam Default"},
	},
	{
		Key:         "soulmask",
		Aliases:     []string{"soul mask"},
		ImageEnv:    "SOULMASK_DOCKER_IMAGE",
		Image:       "vortanix/soulmask:latest",
		Name:        "Soulmask",
		Description: "Soulmask dedicated server.",
		Code:        "soulmask",
		MinPort:     7777,
		MaxPort:     7900,
		PortEnv:     "GAME_PORT",
		Ports:       []PortSpec{{Offset: 0, Protocol: "udp", Purpose: "игровой сервер"}, {Offset: 1, Protocol: "udp", Purpose: "Query"}},
		QueryProto:  QueryA2S,
		MinRAMMB:    10240,
		RecRAMMB:    16384,
		MinDiskMB:   20480,
		MinCPU:      4,
		Install:     Install{SourceType: SourceSteam, SteamAppID: 3017300, Version: "Steam Default"},
	},
	{
		Key:         "spaceeng",
		Aliases:     []string{"space engineers", "space-engineers", "space_engineers"},
		ImageEnv:    "SPACE_ENGINEERS_DOCKER_IMAGE",
		Image:       "vortanix/spaceeng:latest",
		Name:        "Space Engineers",
		Description: "Space Engineers dedicated server.",
		Code:        "spaceeng",
		MinPort:     27016,
		MaxPort:     27100,
		PortEnv:     "GAME_PORT",
		Ports:       []PortSpec{{Offset: 0, Protocol: "udp", Purpose: "игровой сервер"}, {Offset: 1, Protocol: "udp", Purpose: "Steam query"}},
		QueryProto:  QueryA2S,
		MinRAMMB:    8192,
		RecRAMMB:    12288,
		MinDiskMB:   15360,
		MinCPU:      4,
		Install:     Install{SourceType: SourceSteam, SteamAppID: 298740, Version: "Steam Default", Note: "выделенный сервер Space Engineers существует только под Windows — на Linux-ноде не поедет"},
	},
	{
		Key:         "squad",
		Aliases:     []string{"squad server"},
		ImageEnv:    "SQUAD_DOCKER_IMAGE",
		Image:       "vortanix/squad:latest",
		Name:        "Squad",
		Description: "Squad dedicated server.",
		Code:        "squad",
		MinPort:     7787,
		MaxPort:     7900,
		PortEnv:     "GAME_PORT",
		Ports:       []PortSpec{{Offset: 0, Protocol: "udp", Purpose: "игровой сервер"}, {Offset: 1, Protocol: "udp", Purpose: "Query"}, {Offset: 10, Protocol: "tcp", Purpose: "RCON"}},
		QueryProto:  QueryA2S,
		MaxSlots:    100,
		MinRAMMB:    8192,
		RecRAMMB:    12288,
		MinDiskMB:   92160,
		MinCPU:      4,
		Install:     Install{SourceType: SourceSteam, SteamAppID: 403240, Version: "Steam Default"},
	},
	{
		Key:           "starrupt",
		Aliases:       []string{"star rupture", "star-rupture", "star_rupture"},
		ImageEnv:      "STAR_RUPTURE_DOCKER_IMAGE",
		Image:         "vortanix/starrupt:latest",
		Name:          "StarRupture",
		Description:   "StarRupture server profile.",
		Code:          "starrupt",
		MinPort:       25000,
		MaxPort:       25100,
		PortEnv:       "GAME_PORT",
		Ports:         []PortSpec{{Offset: 0, Protocol: "udp", Purpose: "игровой сервер"}, {Offset: 1, Protocol: "udp", Purpose: "Query"}},
		QueryProto:    QueryA2S,
		MinRAMMB:      6144,
		RecRAMMB:      8192,
		MinDiskMB:     15360,
		MinCPU:        2,
		Install:       Install{SourceType: SourceDocker, Version: "Manual"},
		NoLinuxServer: "app 2457320 — это DLC «Fantasy Grounds - FG Completed Maps Pack 5»; у StarRupture (1631270) серверного приложения в Steam нет, депоты только windows",
	},
	{
		Key:         "tf2",
		Aliases:     []string{"teamfortress2", "team_fortress_2", "tf"},
		ImageEnv:    "TF2_DOCKER_IMAGE",
		Image:       "vortanix/tf2:latest",
		Name:        "Team Fortress 2",
		Description: "Team Fortress 2 dedicated server (Source)",
		Code:        "tf2",
		MinPort:     27015,
		MaxPort:     27060,
		PortEnv:     "TF2_PORT",
		Ports:       []PortSpec{{Offset: 0, Protocol: "udp", Purpose: "игровой сервер"}, {Offset: 0, Protocol: "tcp", Purpose: "RCON"}},
		QueryProto:  QueryA2S,
		MaxSlots:    32,
		MinRAMMB:    1024,
		RecRAMMB:    1536,
		MinDiskMB:   25600,
		MinCPU:      1,
		Install:     Install{SourceType: SourceSteam, SteamAppID: 232250, Version: "Steam Default"},
	},
	{
		Key:         "theisle",
		Aliases:     []string{"the isle", "the-isle", "the_isle"},
		ImageEnv:    "THE_ISLE_DOCKER_IMAGE",
		Image:       "vortanix/theisle:latest",
		Name:        "The Isle",
		Description: "The Isle dedicated server.",
		Code:        "theisle",
		MinPort:     7777,
		MaxPort:     7900,
		PortEnv:     "GAME_PORT",
		Ports:       []PortSpec{{Offset: 0, Protocol: "udp", Purpose: "игровой сервер"}, {Offset: 1, Protocol: "udp", Purpose: "Steam query"}},
		QueryProto:  QueryA2S,
		MinRAMMB:    8192,
		RecRAMMB:    12288,
		MinDiskMB:   20480,
		MinCPU:      4,
		Install:     Install{SourceType: SourceSteam, SteamAppID: 412680, Version: "Steam Default"},
	},
	{
		Key:           "ttworlds",
		Aliases:       []string{"terratech worlds", "terratech-worlds", "terratech_worlds"},
		ImageEnv:      "TERRATECH_WORLDS_DOCKER_IMAGE",
		Image:         "vortanix/ttworlds:latest",
		Name:          "TerraTech Worlds",
		Description:   "TerraTech Worlds dedicated server.",
		Code:          "ttworlds",
		MinPort:       7777,
		MaxPort:       7900,
		PortEnv:       "GAME_PORT",
		Ports:         []PortSpec{{Offset: 0, Protocol: "udp", Purpose: "игровой сервер"}, {Offset: 1, Protocol: "udp", Purpose: "Query"}},
		QueryProto:    QueryA2S,
		MinRAMMB:      8192,
		RecRAMMB:      12288,
		MinDiskMB:     15360,
		MinCPU:        4,
		Install:       Install{SourceType: SourceDocker, Version: "Manual"},
		NoLinuxServer: "app 3189360 в Steam не существует; у TerraTech Worlds (2313330) серверного приложения в Steam нет, депоты только windows",
	},
	{
		Key:         "unturned",
		Aliases:     []string{"unturn", "ut"},
		ImageEnv:    "UNTURNED_DOCKER_IMAGE",
		Image:       "vortanix/unturned:latest",
		Name:        "Unturned (Vanilla)",
		Description: "Unturned dedicated server (no mods)",
		Code:        "unturn",
		MinPort:     27015,
		MaxPort:     27060,
		PortEnv:     "UNTURNED_PORT",
		Ports:       []PortSpec{{Offset: 0, Protocol: "udp", Purpose: "игровой сервер"}, {Offset: 1, Protocol: "udp", Purpose: "Steam query"}},
		QueryProto:  QueryA2S,
		MaxSlots:    24,
		MinRAMMB:    1024,
		RecRAMMB:    2048,
		MinDiskMB:   4096,
		MinCPU:      1,
		Install:     Install{SourceType: SourceSteam, SteamAppID: 1110390, Version: "Steam Default"},
	},
	{
		Key:         "untrm4",
		Aliases:     nil,
		ImageEnv:    "UNTURNED_DOCKER_IMAGE",
		Image:       "vortanix/unturned:latest",
		Name:        "Unturned (RocketMod 4)",
		Description: "Unturned dedicated server with RocketMod 4",
		Code:        "untrm4",
		MinPort:     27015,
		MaxPort:     27060,
		PortEnv:     "UNTURNED_PORT",
		Ports:       []PortSpec{{Offset: 0, Protocol: "udp", Purpose: "игровой сервер"}, {Offset: 1, Protocol: "udp", Purpose: "Steam query"}},
		QueryProto:  QueryA2S,
		MaxSlots:    24,
		MinRAMMB:    1024,
		RecRAMMB:    2048,
		MinDiskMB:   4096,
		MinCPU:      1,
		Install: Install{
			SourceType: SourceSteam, SteamAppID: 1110390,
			Version: "Steam Default (RocketMod 4)",
			Note:    "RocketMod 4 ставится поверх ванильных файлов админом",
		},
	},
	{
		Key:         "untrm5",
		Aliases:     nil,
		ImageEnv:    "UNTURNED_DOCKER_IMAGE",
		Image:       "vortanix/unturned:latest",
		Name:        "Unturned (RocketMod 5)",
		Description: "Unturned dedicated server with RocketMod 5",
		Code:        "untrm5",
		MinPort:     27015,
		MaxPort:     27060,
		PortEnv:     "UNTURNED_PORT",
		Ports:       []PortSpec{{Offset: 0, Protocol: "udp", Purpose: "игровой сервер"}, {Offset: 1, Protocol: "udp", Purpose: "Steam query"}},
		QueryProto:  QueryA2S,
		MaxSlots:    24,
		MinRAMMB:    1024,
		RecRAMMB:    2048,
		MinDiskMB:   4096,
		MinCPU:      1,
		Install: Install{
			SourceType: SourceSteam, SteamAppID: 1110390,
			Version: "Steam Default (RocketMod 5)",
			Note:    "RocketMod 5 ставится поверх ванильных файлов админом",
		},
	},
	{
		Key:         "valheim",
		Aliases:     []string{"valheim-server"},
		ImageEnv:    "VALHEIM_DOCKER_IMAGE",
		Image:       "vortanix/valheim:latest",
		Name:        "Valheim",
		Description: "Valheim dedicated server.",
		Code:        "valheim",
		MinPort:     2456,
		MaxPort:     2480,
		PortEnv:     "GAME_PORT",
		Ports:       []PortSpec{{Offset: 0, Protocol: "udp", Purpose: "игровой сервер"}, {Offset: 1, Protocol: "udp", Purpose: "Query"}, {Offset: 2, Protocol: "udp", Purpose: "peer/listen"}},
		QueryProto:  QueryA2S,
		MaxSlots:    10,
		MinRAMMB:    2048,
		RecRAMMB:    4096,
		MinDiskMB:   3072,
		MinCPU:      2,
		Install:     Install{SourceType: SourceSteam, SteamAppID: 896660, Version: "Steam Default"},
	},
	{
		Key:         "vrising",
		Aliases:     []string{"v-rising", "v_rising"},
		ImageEnv:    "VRISING_DOCKER_IMAGE",
		Image:       "vortanix/vrising:latest",
		Name:        "V Rising",
		Description: "V Rising dedicated server.",
		Code:        "vrising",
		MinPort:     9876,
		MaxPort:     9900,
		PortEnv:     "GAME_PORT",
		Ports:       []PortSpec{{Offset: 0, Protocol: "udp", Purpose: "игровой сервер"}, {Offset: 1, Protocol: "udp", Purpose: "Query"}, {Offset: 2, Protocol: "tcp", Purpose: "RCON"}},
		QueryProto:  QueryA2S,
		MinRAMMB:    4096,
		RecRAMMB:    6144,
		MinDiskMB:   10240,
		MinCPU:      2,
		Install:     Install{SourceType: SourceSteam, SteamAppID: 1829350, Version: "Steam Default"},
	},
}
