package gamecatalog

var launches = map[string]Launch{
	"7d2d":      {Runtime: RuntimeSteam, PortEnv: "GAME_PORT", Binaries: []string{"./startserver.sh", "./7DaysToDieServer.x86_64", "./7DaysToDieServer.x86", "./start-server.sh", "./start.sh", "./server.sh", "./run.sh"}},
	"arksa":     {Runtime: RuntimeSteam, PortEnv: "GAME_PORT", Binaries: []string{"./ShooterGame/Binaries/Linux/ArkAscendedServer-Linux-Shipping", "./ShooterGame/Binaries/Linux/ShooterGameServer", "./start-server.sh", "./start.sh", "./server.sh", "./run.sh"}},
	"arkse":     {Runtime: RuntimeSteam, PortEnv: "GAME_PORT", Binaries: []string{"./ShooterGame/Binaries/Linux/ShooterGameServer", "./ShooterGame/Binaries/Linux/ArkAscendedServer-Linux-Shipping", "./start-server.sh", "./start.sh", "./server.sh", "./run.sh"}},
	"arma3":     {Runtime: RuntimeSteam, PortEnv: "GAME_PORT", Binaries: []string{"./arma3server_x64", "./arma3server", "./start-server.sh", "./start.sh", "./server.sh", "./run.sh"}},
	"armaref":   {Runtime: RuntimeSteam, PortEnv: "GAME_PORT", Binaries: []string{"./ArmaReforgerServer", "./ArmaReforgerServer.x86_64", "./start-server.sh", "./start.sh", "./server.sh", "./run.sh"}},
	"bbermuda":  {Runtime: RuntimeSteam, PortEnv: "GAME_PORT", Binaries: []string{"./BeastsOfBermuda/Binaries/Linux/BeastsOfBermudaServer-Linux-Shipping", "./BeastsOfBermudaServer.sh", "./start-server.sh", "./start.sh", "./server.sh", "./run.sh"}},
	"conan":     {Runtime: RuntimeSteam, PortEnv: "GAME_PORT", Binaries: []string{"./ConanSandbox/Binaries/Linux/ConanSandboxServer-Linux-Shipping", "./ConanSandboxServer-Linux-Shipping", "./start-server.sh", "./start.sh", "./server.sh", "./run.sh"}},
	"crmp":      {Runtime: RuntimeNative, PortEnv: "CRMP_PORT"},
	"cs16":      {Runtime: RuntimeSrcds, PortEnv: "CS16_PORT", Params: map[string]string{"mod": "cstrike", "map": "de_dust2", "maxplayers": "32"}},
	"cs2":       {Runtime: RuntimeSteam, PortEnv: "CS2_PORT"},
	"css":       {Runtime: RuntimeSrcds, PortEnv: "CSS_PORT", Params: map[string]string{"mod": "cstrike", "map": "de_dust2", "maxplayers": "32"}},
	"daydrag":   {Runtime: RuntimeSteam, PortEnv: "GAME_PORT", Binaries: []string{"./DayOfDragons/Binaries/Linux/DayOfDragonsServer-Linux-Shipping", "./DayOfDragonsServer.sh", "./start-server.sh", "./start.sh", "./server.sh", "./run.sh"}},
	"dayz":      {Runtime: RuntimeSteam, PortEnv: "GAME_PORT", Binaries: []string{"./DayZServer_x64", "./DayZServer", "./start-server.sh", "./start.sh", "./server.sh", "./run.sh"}},
	"dayzdev":   {Runtime: RuntimeSteam, PortEnv: "GAME_PORT", Binaries: []string{"./DayZServer_x64", "./DayZServer", "./start-server.sh", "./start.sh", "./server.sh", "./run.sh"}},
	"draconia":  {Runtime: RuntimeSteam, PortEnv: "GAME_PORT", Binaries: []string{"./Draconia/Binaries/Linux/DraconiaServer-Linux-Shipping", "./DraconiaServer.sh", "./start-server.sh", "./start.sh", "./server.sh", "./run.sh"}},
	"empyrion":  {Runtime: RuntimeSteam, PortEnv: "GAME_PORT", Binaries: []string{"./EmpyrionDedicated.sh", "./EmpyrionDedicated", "./start-server.sh", "./start.sh", "./server.sh", "./run.sh"}},
	"enshroud":  {Runtime: RuntimeSteam, PortEnv: "GAME_PORT", Binaries: []string{"./enshrouded_server.x86_64", "./EnshroudedServer.sh", "./start-server.sh", "./start.sh", "./server.sh", "./run.sh"}},
	"factorio":  {Runtime: RuntimeSteam, PortEnv: "GAME_PORT", Binaries: []string{"./bin/x64/factorio", "./factorio/bin/x64/factorio", "./start-server.sh", "./start.sh", "./server.sh", "./run.sh"}},
	"gmod":      {Runtime: RuntimeSrcds, PortEnv: "GMOD_PORT", Params: map[string]string{"mod": "garrysmod", "map": "gm_construct", "maxplayers": "24"}},
	"hytale":    {Runtime: RuntimeSteam, PortEnv: "GAME_PORT", Binaries: []string{"./HytaleServer.sh", "./HytaleServer", "./start-server.sh", "./start.sh", "./server.sh", "./run.sh"}},
	"icarus":    {Runtime: RuntimeSteam, PortEnv: "GAME_PORT", Binaries: []string{"./IcarusServer.sh", "./Icarus/Binaries/Linux/IcarusServer-Linux-Shipping", "./start-server.sh", "./start.sh", "./server.sh", "./run.sh"}},
	"isleevr":   {Runtime: RuntimeSteam, PortEnv: "GAME_PORT", Binaries: []string{"./TheIsle/Binaries/Linux/TheIsleServer-Linux-Shipping", "./TheIsleEvrimaServer.sh", "./start-server.sh", "./start.sh", "./server.sh", "./run.sh"}},
	"lifeyo":    {Runtime: RuntimeSteam, PortEnv: "GAME_PORT", Binaries: []string{"./LiF_YourOwn_Server.x64", "./LiF_YourOwn_Server", "./start-server.sh", "./start.sh", "./server.sh", "./run.sh"}},
	"mcbedrock": {Runtime: RuntimeNative, PortEnv: "SERVER_PORT"},
	"mcjava":    {Runtime: RuntimeJava, PortEnv: "SERVER_PORT"},
	"mordhau":   {Runtime: RuntimeSteam, PortEnv: "GAME_PORT", Binaries: []string{"./MordhauServer.sh", "./Mordhau/Binaries/Linux/MordhauServer-Linux-Shipping", "./start-server.sh", "./start.sh", "./server.sh", "./run.sh"}},
	"mta":       {Runtime: RuntimeNative, PortEnv: "MTA_PORT"},
	"nosurv":    {Runtime: RuntimeSteam, PortEnv: "GAME_PORT", Binaries: []string{"./NoOneSurvived/Binaries/Linux/NoOneSurvivedServer-Linux-Shipping", "./NoOneSurvivedServer.sh", "./start-server.sh", "./start.sh", "./server.sh", "./run.sh"}},
	"palworld":  {Runtime: RuntimeSteam, PortEnv: "GAME_PORT", Binaries: []string{"./PalServer.sh", "./Pal/Binaries/Linux/PalServer-Linux-Shipping", "./start-server.sh", "./start.sh", "./server.sh", "./run.sh"}},
	"pathtit":   {Runtime: RuntimeSteam, PortEnv: "GAME_PORT", Binaries: []string{"./PathOfTitansServer.sh", "./AlderonGamesCmd-Linux/pathoftitansserver.sh", "./start-server.sh", "./start.sh", "./server.sh", "./run.sh"}},
	"pzomboid":  {Runtime: RuntimeSteam, PortEnv: "GAME_PORT", Binaries: []string{"./start-server.sh", "./ProjectZomboid64", "./start.sh", "./server.sh", "./run.sh"}},
	"rs2vn":     {Runtime: RuntimeSteam, PortEnv: "GAME_PORT", Binaries: []string{"./Binaries/Linux/RS2Server-Linux-Shipping", "./RS2Server.sh", "./start-server.sh", "./start.sh", "./server.sh", "./run.sh"}},
	"rust":      {Runtime: RuntimeSteam, PortEnv: "RUST_PORT"},
	"samp":      {Runtime: RuntimeNative, PortEnv: "SAMP_PORT"},
	"satisfac":  {Runtime: RuntimeSteam, PortEnv: "GAME_PORT", Binaries: []string{"./FactoryServer.sh", "./Engine/Binaries/Linux/FactoryServer-Linux-Shipping", "./start-server.sh", "./start.sh", "./server.sh", "./run.sh"}},
	"scum":      {Runtime: RuntimeSteam, PortEnv: "GAME_PORT", Binaries: []string{"./SCUM/Binaries/Linux/SCUMServer-Linux-Shipping", "./SCUMServer.sh", "./start-server.sh", "./start.sh", "./server.sh", "./run.sh"}},
	"sotf":      {Runtime: RuntimeSteam, PortEnv: "GAME_PORT", Binaries: []string{"./SonsOfTheForestDS", "./SonsOfTheForest/Binaries/Linux/SonsOfTheForestDS.x86_64", "./start-server.sh", "./start.sh", "./server.sh", "./run.sh"}},
	"soulmask":  {Runtime: RuntimeSteam, PortEnv: "GAME_PORT", Binaries: []string{"./Soulmask/Binaries/Linux/SoulmaskServer-Linux-Shipping", "./SoulmaskServer.sh", "./start-server.sh", "./start.sh", "./server.sh", "./run.sh"}},
	"spaceeng":  {Runtime: RuntimeSteam, PortEnv: "GAME_PORT", Binaries: []string{"./SpaceEngineersDedicated", "./DedicatedServer64/SpaceEngineersDedicated", "./start-server.sh", "./start.sh", "./server.sh", "./run.sh"}},
	"squad":     {Runtime: RuntimeSteam, PortEnv: "GAME_PORT", Binaries: []string{"./SquadGameServer.sh", "./Squad/Binaries/Linux/SquadGameServer", "./start-server.sh", "./start.sh", "./server.sh", "./run.sh"}},
	"starrupt":  {Runtime: RuntimeSteam, PortEnv: "GAME_PORT", Binaries: []string{"./StarRupture/Binaries/Linux/StarRuptureServer-Linux-Shipping", "./StarRuptureServer.sh", "./start-server.sh", "./start.sh", "./server.sh", "./run.sh"}},
	"tf2":       {Runtime: RuntimeSrcds, PortEnv: "TF2_PORT", Params: map[string]string{"mod": "tf", "map": "ctf_2fort", "maxplayers": "24"}},
	"theisle":   {Runtime: RuntimeSteam, PortEnv: "GAME_PORT", Binaries: []string{"./TheIsle/Binaries/Linux/TheIsleServer-Linux-Shipping", "./TheIsleServer.sh", "./start-server.sh", "./start.sh", "./server.sh", "./run.sh"}},
	"ttworlds":  {Runtime: RuntimeSteam, PortEnv: "GAME_PORT", Binaries: []string{"./TerraTechWorlds/Binaries/Linux/TerraTechWorldsServer-Linux-Shipping", "./TerraTechWorldsServer.sh", "./start-server.sh", "./start.sh", "./server.sh", "./run.sh"}},
	"unturned":  {Runtime: RuntimeSteam, PortEnv: "UNTURNED_PORT"},
	"valheim":   {Runtime: RuntimeSteam, PortEnv: "GAME_PORT", Binaries: []string{"./valheim_server.x86_64", "./start-server.sh", "./start.sh", "./server.sh", "./run.sh"}},
	"vrising":   {Runtime: RuntimeSteam, PortEnv: "GAME_PORT", Binaries: []string{"./VRisingServer.sh", "./VRisingServer/Binaries/Linux/VRisingServer-Linux-Shipping", "./start-server.sh", "./start.sh", "./server.sh", "./run.sh"}},
	"mcpaper":   {Runtime: RuntimeJava, PortEnv: "SERVER_PORT"},
	"mcspigot":  {Runtime: RuntimeJava, PortEnv: "SERVER_PORT"},
	"mcforge":   {Runtime: RuntimeJava, PortEnv: "SERVER_PORT"},
	"mcfabric":  {Runtime: RuntimeJava, PortEnv: "SERVER_PORT"},
	"untrm4":    {Runtime: RuntimeSteam, PortEnv: "UNTURNED_PORT"},
	"untrm5":    {Runtime: RuntimeSteam, PortEnv: "UNTURNED_PORT"},
}
