export const queryKeys = {
  me: ["me"] as const,
  tenantStatus: ["tenant-status"] as const,
  users: ["users"] as const,
  nodes: ["nodes"] as const,
  servers: ["servers"] as const,
  server: (id: string) => ["servers", id] as const,
  serverDetail: (id: string) => ["servers", id, "detail"] as const,
  metrics: (id: string) => ["metrics", id] as const,
  billing: (walletId?: string | null) =>
    ["billing", walletId ?? "default"] as const,
  billingTopup: () => ["billing-topup"] as const,
  billingPayment: (id: string) => ["billing-payment", id] as const,
  supportTickets: ["support-tickets"] as const,
  supportCreateForm: ["support-create-form"] as const,
  kbArticles: (category?: string, q?: string) => ["kb-articles", category ?? "", q ?? ""] as const,
  kbArticle: (slug: string) => ["kb-article", slug] as const,
  adminKbArticles: ["admin-kb-articles"] as const,
  supportTicket: (id: string) => ["support-ticket", id] as const,
  hostingMy: ["hosting-my"] as const,
  hostingRent: ["hosting-rent"] as const,
  hostingAccount: (id: string) => ["hosting-account", id] as const,
  newsList: ["news"] as const,
  newsItem: (slug: string) => ["news", slug] as const,
  rentCatalog: ["rent-catalog"] as const,
  rentServer: (params: Record<string, string>) => ["rent-server", params] as const,
  serverStatus: (id: string) => ["servers", id, "status"] as const,
  serverMapsFolder: (id: string) => ["servers", id, "maps-folder"] as const,
  serverPlugins: (id: string) => ["servers", id, "plugins"] as const,
  serverMaps: (id: string) => ["servers", id, "maps"] as const,
  serverPorts: (id: string) => ["servers", id, "ports"] as const,
  serverMysql: (id: string) => ["servers", id, "mysql"] as const,
  monitoring: ["monitoring"] as const,
  monitoringServer: (id: string) => ["monitoring-server", id] as const,
  monitoringServerStats: (id: string, days: number) => ["monitoring-server-stats", id, days] as const,
  monitoringPublic: (id: string) => ["monitoring-public", id] as const,
  monitoringPublicLive: (id: string) => ["monitoring-public-live", id] as const,
  monitoringPublicStats: (id: string, days: number) => ["monitoring-public-stats", id, days] as const,
  monitoringTop: (game?: string) => ["monitoring-top", game ?? ""] as const,
  monitoringSettings: (id: string) => ["monitoring-settings", id] as const,
  monitoringIncidents: (id: string) => ["monitoring-incidents", id] as const,
  monitoringLogs: (id: string) => ["monitoring-logs", id] as const,
  adminDashboard: ["admin-dashboard"] as const,
  adminDashboardNodes: ["admin-dashboard", "nodes"] as const,
  adminSupport: ["admin-support"] as const,
  adminUsers: (page?: number, q?: string, role?: string) =>
    ["admin-users", page ?? 1, q ?? "", role ?? ""] as const,
  adminUser: (id: string) => ["admin-user", id] as const,
  adminUserEdit: (id: string) => ["admin-user", id, "edit"] as const,
  adminLocations: ["admin-locations"] as const,
  adminNodes: ["admin-locations", "nodes"] as const,
  adminLocation: (id: string) => ["admin-location", id] as const,
  adminLocationEdit: (id: string) => ["admin-location", id, "edit"] as const,
  adminLocationSetup: (id: string) => ["admin-location", id, "setup"] as const,
  adminLocationDaemon: (id: string) => ["admin-location", id, "daemon"] as const,
  adminTariffs: (page?: number, filters?: Record<string, string>) =>
    page != null
      ? (["admin-tariffs", page, filters ?? {}] as const)
      : (["admin-tariffs"] as const),
  adminTariff: (id: string) => ["admin-tariff", id] as const,
  adminTariffEdit: (id: string) => ["admin-tariff", id, "edit"] as const,
  adminTariffCreate: ["admin-tariff-create"] as const,
  adminGames: ["admin-games"] as const,
  adminGame: (id: string) => ["admin-game", id] as const,
  adminGameEdit: (id: string) => ["admin-game", id, "edit"] as const,
  adminGroups: ["admin-groups"] as const,
  adminPaymentProviders: ["admin-payment-providers"] as const,
  adminSettings: ["admin-settings"] as const,
  adminReadiness: ["admin-readiness"] as const,
  adminServers: ["admin-servers"] as const,
  adminAppearance: ["admin-appearance"] as const,
  adminAgents: ["admin-agents"] as const,
  adminAgent: (id: string) => ["admin-agent", id] as const,
  adminAgentLogs: (id: string) => ["admin-agent", id, "logs"] as const,
  adminAgentServers: (id: string) => ["admin-agent", id, "servers"] as const,
  adminImages: ["admin-images"] as const,
  adminUpdates: ["admin-updates"] as const,
};
