import {
  Activity,
  ArrowRight,
  AtSign,
  Award,
  BadgePercent,
  Banknote,
  Bell,
  Blocks,
  BookMarked,
  BookOpen,
  Bot,
  Box,
  Boxes,
  Briefcase,
  Bug,
  Building2,
  Calculator,
  Calendar,
  Camera,
  Castle,
  ChartBar,
  ChartLine,
  ChartPie,
  Check,
  CircleHelp,
  CirclePlus,
  CircleUser,
  ClipboardList,
  Clock,
  Cloud,
  CloudDownload,
  Code,
  Cog,
  Coins,
  Compass,
  Copy,
  Cpu,
  CreditCard,
  Crosshair,
  Crown,
  Database,
  Dices,
  Download,
  ExternalLink,
  Eye,
  FileImage,
  FileQuestion,
  FileText,
  Film,
  Flag,
  Flame,
  Folder,
  Gamepad2,
  Gauge,
  Gem,
  Gift,
  Globe,
  GraduationCap,
  Hammer,
  Handshake,
  HardDrive,
  Hash,
  Headphones,
  Headset,
  Heart,
  History,
  House,
  Image,
  Inbox,
  Info,
  Joystick,
  Key,
  Languages,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  LifeBuoy,
  Lightbulb,
  Link,
  List,
  ListChecks,
  Lock,
  LogIn,
  Mail,
  Map,
  MapPin,
  Medal,
  Megaphone,
  MemoryStick,
  MessageCircle,
  MessageSquare,
  MessagesSquare,
  Mic,
  Monitor,
  Moon,
  Music,
  Network,
  Newspaper,
  Package,
  Palette,
  PenLine,
  Percent,
  Phone,
  PiggyBank,
  Play,
  Plug,
  Power,
  Puzzle,
  Radio,
  Receipt,
  RefreshCw,
  Rocket,
  Rss,
  Satellite,
  Scale,
  Scroll,
  Search,
  Send,
  Server,
  Settings,
  Share2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShoppingCart,
  Siren,
  SlidersHorizontal,
  Smile,
  Sparkles,
  Star,
  Store,
  Sun,
  Sword,
  Swords,
  Tag,
  Target,
  Terminal,
  ThumbsUp,
  Ticket,
  Timer,
  Trophy,
  Truck,
  Tv,
  Upload,
  User,
  UserCog,
  UserPlus,
  Users,
  Video,
  Wallet,
  Webhook,
  Wifi,
  Workflow,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const SITE_ICONS: Record<string, LucideIcon> = {
  home: House,
  "layout-dashboard": LayoutDashboard,
  "layout-grid": LayoutGrid,
  server: Server,
  "hard-drive": HardDrive,
  cpu: Cpu,
  "memory-stick": MemoryStick,
  database: Database,
  network: Network,
  cloud: Cloud,
  "cloud-download": CloudDownload,
  wifi: Wifi,
  globe: Globe,
  terminal: Terminal,
  code: Code,
  bot: Bot,
  workflow: Workflow,
  webhook: Webhook,
  plug: Plug,
  puzzle: Puzzle,
  blocks: Blocks,
  box: Box,
  boxes: Boxes,
  package: Package,
  layers: Layers,
  "gamepad-2": Gamepad2,
  joystick: Joystick,
  swords: Swords,
  sword: Sword,
  crosshair: Crosshair,
  castle: Castle,
  dices: Dices,
  trophy: Trophy,
  medal: Medal,
  award: Award,
  crown: Crown,
  gem: Gem,
  star: Star,
  flame: Flame,
  zap: Zap,
  rocket: Rocket,
  sparkles: Sparkles,
  target: Target,
  gauge: Gauge,
  activity: Activity,
  "chart-line": ChartLine,
  "chart-bar": ChartBar,
  "chart-pie": ChartPie,
  "credit-card": CreditCard,
  wallet: Wallet,
  coins: Coins,
  banknote: Banknote,
  "piggy-bank": PiggyBank,
  receipt: Receipt,
  percent: Percent,
  "badge-percent": BadgePercent,
  tag: Tag,
  gift: Gift,
  ticket: Ticket,
  "shopping-cart": ShoppingCart,
  store: Store,
  calculator: Calculator,
  scale: Scale,
  briefcase: Briefcase,
  "building-2": Building2,
  handshake: Handshake,
  user: User,
  users: Users,
  "user-plus": UserPlus,
  "user-cog": UserCog,
  "circle-user": CircleUser,
  "log-in": LogIn,
  lock: Lock,
  key: Key,
  shield: Shield,
  "shield-check": ShieldCheck,
  "shield-alert": ShieldAlert,
  siren: Siren,
  bug: Bug,
  headphones: Headphones,
  headset: Headset,
  "life-buoy": LifeBuoy,
  "circle-help": CircleHelp,
  "file-question": FileQuestion,
  info: Info,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  "messages-square": MessagesSquare,
  send: Send,
  mail: Mail,
  "at-sign": AtSign,
  phone: Phone,
  bell: Bell,
  megaphone: Megaphone,
  radio: Radio,
  rss: Rss,
  newspaper: Newspaper,
  "book-open": BookOpen,
  "book-marked": BookMarked,
  "graduation-cap": GraduationCap,
  scroll: Scroll,
  "file-text": FileText,
  "file-image": FileImage,
  "clipboard-list": ClipboardList,
  "list-checks": ListChecks,
  list: List,
  folder: Folder,
  inbox: Inbox,
  image: Image,
  camera: Camera,
  video: Video,
  film: Film,
  tv: Tv,
  play: Play,
  music: Music,
  mic: Mic,
  monitor: Monitor,
  satellite: Satellite,
  map: Map,
  "map-pin": MapPin,
  compass: Compass,
  flag: Flag,
  truck: Truck,
  calendar: Calendar,
  clock: Clock,
  timer: Timer,
  history: History,
  "refresh-cw": RefreshCw,
  settings: Settings,
  cog: Cog,
  "sliders-horizontal": SlidersHorizontal,
  wrench: Wrench,
  hammer: Hammer,
  palette: Palette,
  "pen-line": PenLine,
  languages: Languages,
  search: Search,
  eye: Eye,
  link: Link,
  "external-link": ExternalLink,
  "share-2": Share2,
  copy: Copy,
  download: Download,
  upload: Upload,
  hash: Hash,
  heart: Heart,
  "thumbs-up": ThumbsUp,
  smile: Smile,
  lightbulb: Lightbulb,
  sun: Sun,
  moon: Moon,
  power: Power,
  check: Check,
  "circle-plus": CirclePlus,
  "arrow-right": ArrowRight,
};

export const SITE_ICON_NAMES = Object.keys(SITE_ICONS);

export function siteIcon(name: string | undefined): LucideIcon | undefined {
  if (!name) return undefined;
  return SITE_ICONS[name];
}
