package gamesettings

func init() {
	register(Profile{
		Key: "vrising",
		Files: []ConfigFile{
			{ID: "host", Path: "save-data/Settings/ServerHostSettings.json",
				Format: FormatJSON, Title: "ServerHostSettings.json", Template: "{\n}\n"},
			{ID: "game", Path: "save-data/Settings/ServerGameSettings.json",
				Format: FormatJSON, Title: "ServerGameSettings.json", Template: "{\n}\n"},
			{ID: "startup", Path: StartupPath, Format: FormatArgs, Title: "Параметры запуска"},
		},
		Fields: []Field{
			{Key: "name", File: "host", Prop: "Name",
				Label: "Название сервера", Section: SectionGeneral, Kind: KindString, MaxLen: 128},
			{Key: "description", File: "host", Prop: "Description",
				Label: "Описание", Section: SectionGeneral, Kind: KindText, MaxLen: 500, Clearable: true},
			{Key: "password", File: "host", Prop: "Password",
				Label: "Пароль для входа", Section: SectionGeneral,
				Kind: KindString, MaxLen: 128, Secret: true, Clearable: true},
			{Key: "max_users", File: "host", Prop: "MaxConnectedUsers", Slots: true,
				Label: "Мест на сервере", Section: SectionGeneral,
				Kind: KindInt, Min: AtLeast(1), Max: AtMost(100)},
			{Key: "max_admins", File: "host", Prop: "MaxConnectedAdmins",
				Label: "Мест сверх лимита для администраторов", Section: SectionAdmin,
				Kind: KindInt, Min: AtLeast(0), Max: AtMost(20), Default: "4"},
			{Key: "save_name", File: "host", Prop: "SaveName",
				Label: "Имя сохранения", Section: SectionWorld, Kind: KindString, MaxLen: 128,
				Hint: "Смена открывает другой мир, а не переносит текущий"},
			{Key: "list_on_master", File: "host", Prop: "ListOnMasterServer",
				Label: "Показывать в общем списке", Section: SectionNetwork,
				Kind: KindBool, Default: "true"},
			{Key: "server_fps", File: "host", Prop: "ServerFps",
				Label: "Частота обновления, кадров", Section: SectionPerformance,
				Kind: KindInt, Min: AtLeast(20), Max: AtMost(60), Default: "30"},
			{Key: "autosave_count", File: "host", Prop: "AutoSaveCount",
				Label: "Число копий", Section: SectionSaves,
				Kind: KindInt, Min: AtLeast(1), Max: AtMost(100), Default: "20"},
			{Key: "autosave_interval", File: "host", Prop: "AutoSaveInterval",
				Label: "Интервал автосохранения, с", Section: SectionSaves,
				Kind: KindInt, Min: AtLeast(60), Max: AtMost(86400), Default: "120"},
			{Key: "rcon_enabled", File: "host", Prop: "Rcon.Enabled",
				Label: "Удалённое управление", Section: SectionAdmin, Kind: KindBool},
			{Key: "rcon_password", File: "host", Prop: "Rcon.Password",
				Label: "Пароль RCON", Section: SectionAdmin,
				Kind: KindString, MaxLen: 128, Secret: true, Clearable: true},

			{Key: "game_mode", File: "game", Prop: "GameModeType",
				Label: "Режим игры", Section: SectionGameplay, Kind: KindEnum, Default: "PvP",
				Options: []Option{
					{Value: "PvE", Label: "Без боя между игроками"},
					{Value: "PvP", Label: "С боем между игроками"},
				}},
			{Key: "castle_damage", File: "game", Prop: "CastleDamageMode",
				Label: "Урон по замкам", Section: SectionGameplay, Kind: KindEnum, Default: "TimeRestricted",
				Options: []Option{
					{Value: "Never", Label: "Запрещён"},
					{Value: "TimeRestricted", Label: "По расписанию"},
					{Value: "Always", Label: "Всегда"},
				}},
			{Key: "clan_size", File: "game", Prop: "ClanSize",
				Label: "Размер клана", Section: SectionGameplay,
				Kind: KindInt, Min: AtLeast(1), Max: AtMost(50), Default: "4"},
			{Key: "blood_drain", File: "game", Prop: "BloodDrainModifier",
				Label: "Расход крови", Section: SectionRates,
				Kind: KindFloat, Min: AtLeast(0), Max: AtMost(10), Default: "1.0"},
			{Key: "material_yield", File: "game", Prop: "MaterialYieldModifier_Global",
				Label: "Множитель добычи", Section: SectionRates,
				Kind: KindFloat, Min: AtLeast(0.1), Max: AtMost(10), Default: "1.0"},
			{Key: "inventory_stacks", File: "game", Prop: "InventoryStacksModifier",
				Label: "Размер стопок в инвентаре", Section: SectionRates,
				Kind: KindFloat, Min: AtLeast(0.1), Max: AtMost(10), Default: "1.0"},
		},
	})

	register(Profile{
		Key: "enshroud",
		Files: []ConfigFile{
			{ID: "main", Path: "enshrouded_server.json", Format: FormatJSON,
				Title: "enshrouded_server.json", Template: "{\n}\n"},
			{ID: "startup", Path: StartupPath, Format: FormatArgs, Title: "Параметры запуска"},
		},
		Fields: []Field{
			{Key: "name", File: "main", Prop: "name",
				Label: "Название сервера", Section: SectionGeneral, Kind: KindString, MaxLen: 128},
			{Key: "slot_count", File: "main", Prop: "slotCount", Slots: true,
				Label: "Мест на сервере", Section: SectionGeneral,
				Kind: KindInt, Min: AtLeast(1), Max: AtMost(16)},
			{Key: "save_directory", File: "main", Prop: "saveDirectory",
				Label: "Каталог сохранений", Section: SectionWorld,
				Kind: KindString, MaxLen: 128, Default: "./savegame"},
			{Key: "admin_password", File: "main", Prop: "userGroups[name=Admin].password",
				Label: "Пароль администратора", Section: SectionAdmin,
				Kind: KindString, MaxLen: 128, Secret: true},
			{Key: "friend_password", File: "main", Prop: "userGroups[name=Friend].password",
				Label: "Пароль для друзей", Section: SectionGeneral,
				Kind: KindString, MaxLen: 128, Secret: true, Clearable: true},
			{Key: "guest_password", File: "main", Prop: "userGroups[name=Guest].password",
				Label: "Пароль для гостей", Section: SectionGeneral,
				Kind: KindString, MaxLen: 128, Secret: true, Clearable: true},
			{Key: "voice_chat", File: "main", Prop: "enableVoiceChat",
				Label: "Голосовой чат", Section: SectionPlayers, Kind: KindBool},
			{Key: "text_chat", File: "main", Prop: "enableTextChat",
				Label: "Текстовый чат", Section: SectionPlayers, Kind: KindBool},
			{Key: "preset", File: "main", Prop: "gameSettingsPreset",
				Label: "Набор правил", Section: SectionGameplay, Kind: KindEnum, Default: "Default",
				Options: []Option{
					{Value: "Default", Label: "Обычный"},
					{Value: "Relaxed", Label: "Спокойный"},
					{Value: "Hard", Label: "Тяжёлый"},
					{Value: "Survival", Label: "Выживание"},
					{Value: "Custom", Label: "Свой"},
				},
				Hint: "Множители ниже действуют только при своём наборе правил"},
			{Key: "enemy_damage", File: "main", Prop: "gameSettings.enemyDamageFactor",
				Label: "Урон врагов", Section: SectionRates,
				Kind: KindFloat, Min: AtLeast(0.1), Max: AtMost(10), Default: "1.0"},
			{Key: "enemy_health", File: "main", Prop: "gameSettings.enemyHealthFactor",
				Label: "Здоровье врагов", Section: SectionRates,
				Kind: KindFloat, Min: AtLeast(0.1), Max: AtMost(10), Default: "1.0"},
			{Key: "mining_damage", File: "main", Prop: "gameSettings.miningDamageFactor",
				Label: "Скорость добычи", Section: SectionRates,
				Kind: KindFloat, Min: AtLeast(0.1), Max: AtMost(10), Default: "1.0"},
			{Key: "experience_combat", File: "main", Prop: "gameSettings.experienceCombatFactor",
				Label: "Опыт за бой", Section: SectionRates,
				Kind: KindFloat, Min: AtLeast(0.1), Max: AtMost(10), Default: "1.0"},
			{Key: "durability", File: "main", Prop: "gameSettings.enableDurability",
				Label: "Износ снаряжения", Section: SectionGameplay, Kind: KindBool, Default: "true"},
			{Key: "day_duration", File: "main", Prop: "gameSettings.dayTimeDuration",
				Label: "Длительность дня, с", Section: SectionWorld,
				Kind: KindInt, Min: AtLeast(60), Max: AtMost(86400), Default: "1800"},
			{Key: "night_duration", File: "main", Prop: "gameSettings.nightTimeDuration",
				Label: "Длительность ночи, с", Section: SectionWorld,
				Kind: KindInt, Min: AtLeast(60), Max: AtMost(86400), Default: "720"},
		},
	})

	register(Profile{
		Key: "sotf",
		Files: []ConfigFile{
			{ID: "main", Path: "userdata/dedicatedserver.cfg", Format: FormatJSON,
				Title: "dedicatedserver.cfg", Template: "{\n}\n"},
			{ID: "startup", Path: StartupPath, Format: FormatArgs, Title: "Параметры запуска"},
		},
		Note: "Файл dedicatedserver.cfg хранится в формате JSON, несмотря на расширение.",
		Fields: []Field{
			{Key: "server_name", File: "main", Prop: "ServerName",
				Label: "Название сервера", Section: SectionGeneral, Kind: KindString, MaxLen: 128},
			{Key: "max_players", File: "main", Prop: "MaxPlayers", Slots: true,
				Label: "Мест на сервере", Section: SectionGeneral,
				Kind: KindInt, Min: AtLeast(1), Max: AtMost(8)},
			{Key: "password", File: "main", Prop: "Password",
				Label: "Пароль для входа", Section: SectionGeneral,
				Kind: KindString, MaxLen: 128, Secret: true, Clearable: true},
			{Key: "contact", File: "main", Prop: "ServerContactInfo",
				Label: "Контакт администратора", Section: SectionGeneral,
				Kind: KindString, MaxLen: 128, Clearable: true},
			{Key: "lan_only", File: "main", Prop: "LanOnly",
				Label: "Только локальная сеть", Section: SectionNetwork, Kind: KindBool},
			{Key: "game_mode", File: "main", Prop: "GameMode",
				Label: "Режим игры", Section: SectionGameplay, Kind: KindEnum, Default: "Normal",
				Options: []Option{
					{Value: "Peaceful", Label: "Мирный"},
					{Value: "Normal", Label: "Обычный"},
					{Value: "Hard", Label: "Тяжёлый"},
					{Value: "HardSurvival", Label: "Тяжёлое выживание"},
					{Value: "Creative", Label: "Творческий"},
					{Value: "Custom", Label: "Свой"},
				}},
			{Key: "save_slot", File: "main", Prop: "SaveSlot",
				Label: "Слот сохранения", Section: SectionWorld,
				Kind: KindInt, Min: AtLeast(1), Max: AtMost(5), Default: "1"},
			{Key: "save_mode", File: "main", Prop: "SaveMode",
				Label: "Что делать при запуске", Section: SectionWorld, Kind: KindEnum, Default: "Continue",
				Options: []Option{
					{Value: "Continue", Label: "Продолжить сохранение"},
					{Value: "New", Label: "Начать заново"},
				},
				Hint: "«Начать заново» перезапишет текущий слот"},
			{Key: "save_interval", File: "main", Prop: "SaveInterval",
				Label: "Интервал автосохранения, с", Section: SectionSaves,
				Kind: KindInt, Min: AtLeast(60), Max: AtMost(86400), Default: "600"},
			{Key: "idle_day_speed", File: "main", Prop: "IdleDayCycleSpeed",
				Label: "Скорость суток без игроков", Section: SectionWorld,
				Kind: KindFloat, Min: AtLeast(0), Max: AtMost(10), Default: "1.0"},
			{Key: "active_day_speed", File: "main", Prop: "ActiveDayCycleSpeed",
				Label: "Скорость суток с игроками", Section: SectionWorld,
				Kind: KindFloat, Min: AtLeast(0), Max: AtMost(10), Default: "1.0"},
		},
	})

	register(Profile{
		Key: "satisfac",
		Files: []ConfigFile{
			{ID: "main", Path: "FactoryGame/Saved/Config/LinuxServer/ServerSettings.ini",
				Format: FormatINI, Title: "ServerSettings.ini"},
			{ID: "game", Path: "FactoryGame/Saved/Config/LinuxServer/Game.ini",
				Format: FormatINI, Title: "Game.ini"},
			{ID: "engine", Path: "FactoryGame/Saved/Config/LinuxServer/Engine.ini",
				Format: FormatINI, Title: "Engine.ini"},
			{ID: "startup", Path: StartupPath, Format: FormatArgs, Title: "Параметры запуска"},
		},
		Note: "Имя сервера и пароль администратора Satisfactory задаются в игре при первом подключении и в панели не отображаются.",
		Fields: []Field{
			{Key: "max_players", File: "game", Prop: "/Script/Engine.GameSession/MaxPlayers", Slots: true,
				Label: "Мест на сервере", Section: SectionGeneral,
				Kind: KindInt, Min: AtLeast(1), Max: AtMost(16)},
			{Key: "autoload_session", File: "main", Prop: "/Script/FactoryGame.FGServerSubsystem/mAutoLoadSessionName",
				Label: "Загружать сохранение", Section: SectionWorld,
				Kind: KindString, MaxLen: 128, Clearable: true},
			{Key: "auto_pause", File: "main", Prop: "/Script/FactoryGame.FGServerSubsystem/mAutoPause",
				Label: "Пауза без игроков", Section: SectionGameplay,
				Kind: KindBool, True: "True", False: "False", Default: "true"},
			{Key: "auto_save_on_disconnect", File: "main", Prop: "/Script/FactoryGame.FGServerSubsystem/mAutoSaveOnDisconnect",
				Label: "Сохранять при выходе последнего игрока", Section: SectionSaves,
				Kind: KindBool, True: "True", False: "False", Default: "true"},
			{Key: "disable_seasonal_events", File: "main", Prop: "/Script/FactoryGame.FGServerSubsystem/mDisableSeasonalEvents",
				Label: "Отключить сезонные события", Section: SectionGameplay,
				Kind: KindBool, True: "True", False: "False"},
			{Key: "network_quality", File: "main", Prop: "/Script/FactoryGame.FGServerSubsystem/mNetworkQuality",
				Label: "Качество сети", Section: SectionNetwork, Kind: KindEnum, Default: "2",
				Options: []Option{
					{Value: "0", Label: "Низкое"},
					{Value: "1", Label: "Среднее"},
					{Value: "2", Label: "Высокое"},
					{Value: "3", Label: "Максимальное"},
				}},
			{Key: "net_tick_rate", File: "engine", Prop: "/Script/OnlineSubsystemUtils.IpNetDriver/NetServerMaxTickRate",
				Label: "Частота тиков сети", Section: SectionPerformance,
				Kind: KindInt, Min: AtLeast(10), Max: AtMost(120), Default: "30"},
		},
	})

	register(Profile{
		Key: "squad",
		Files: []ConfigFile{
			{ID: "main", Path: "SquadGame/ServerConfig/Server.cfg", Format: FormatProperties,
				Title: "Server.cfg"},
			{ID: "rcon", Path: "SquadGame/ServerConfig/Rcon.cfg", Format: FormatProperties,
				Title: "Rcon.cfg"},
			{ID: "admins", Path: "SquadGame/ServerConfig/Admins.cfg", Format: FormatKVSpace,
				Title: "Admins.cfg", RawOnly: true},
			{ID: "rotation", Path: "SquadGame/ServerConfig/LayerRotation.cfg", Format: FormatKVSpace,
				Title: "LayerRotation.cfg", RawOnly: true},
			{ID: "startup", Path: StartupPath, Format: FormatArgs, Title: "Параметры запуска"},
		},
		Fields: []Field{
			{Key: "server_name", File: "main", Prop: "ServerName",
				Label: "Название сервера", Section: SectionGeneral, Kind: KindString, MaxLen: 128},
			{Key: "max_players", File: "main", Prop: "MaxPlayers", Slots: true,
				Label: "Мест на сервере", Section: SectionGeneral,
				Kind: KindInt, Min: AtLeast(1), Max: AtMost(100)},
			{Key: "reserved_slots", File: "main", Prop: "NumReservedSlots",
				Label: "Мест в резерве", Section: SectionGeneral,
				Kind: KindInt, Min: AtLeast(0), Max: AtMost(50), Default: "0"},
			{Key: "server_password", File: "main", Prop: "ServerPassword",
				Label: "Пароль для входа", Section: SectionGeneral,
				Kind: KindString, MaxLen: 128, Secret: true, Clearable: true},
			{Key: "should_advertise", File: "main", Prop: "ShouldAdvertise",
				Label: "Показывать в общем списке", Section: SectionNetwork,
				Kind: KindBool, True: "true", False: "false", Default: "true"},
			{Key: "is_lan", File: "main", Prop: "IsLANMatch",
				Label: "Только локальная сеть", Section: SectionNetwork,
				Kind: KindBool, True: "true", False: "false"},
			{Key: "public_queue_limit", File: "main", Prop: "PublicQueueLimit",
				Label: "Длина очереди", Section: SectionNetwork,
				Kind: KindInt, Min: AtLeast(0), Max: AtMost(100), Default: "25"},
			{Key: "message_interval", File: "main", Prop: "ServerMessageInterval",
				Label: "Интервал сообщений сервера, с", Section: SectionGeneral,
				Kind: KindInt, Min: AtLeast(0), Max: AtMost(3600)},
			{Key: "use_vote_layer", File: "main", Prop: "UseVoteLayer",
				Label: "Голосование за карту", Section: SectionGameplay,
				Kind: KindBool, True: "true", False: "false"},
			{Key: "vote_duration", File: "main", Prop: "VoteDuration",
				Label: "Длительность голосования, с", Section: SectionGameplay,
				Kind: KindInt, Min: AtLeast(10), Max: AtMost(600), Default: "90"},
			{Key: "allow_team_changes", File: "main", Prop: "AllowTeamChanges",
				Label: "Разрешить смену команды", Section: SectionPlayers,
				Kind: KindBool, True: "true", False: "false", Default: "true"},
			{Key: "tk_autokick", File: "main", Prop: "TKAutoKickEnabled",
				Label: "Кик за урон по своим", Section: SectionPlayers,
				Kind: KindBool, True: "true", False: "false", Default: "true"},
			{Key: "tk_threshold", File: "main", Prop: "TKThreshold",
				Label: "Порог урона по своим", Section: SectionPlayers,
				Kind: KindInt, Min: AtLeast(1), Max: AtMost(100), Default: "6"},
			{Key: "rcon_password", File: "rcon", Prop: "Password",
				Label: "Пароль RCON", Section: SectionAdmin,
				Kind: KindString, MaxLen: 128, Secret: true},
			{Key: "rcon_port", File: "rcon", Prop: "Port",
				Label: "Порт RCON", Section: SectionAdmin,
				Kind: KindInt, Min: AtLeast(1), Max: AtMost(65535), ReadOnly: true},
		},
	})

	dayzFields := []Field{
		{Key: "hostname", File: "main", Prop: "hostname",
			Label: "Название сервера", Section: SectionGeneral, Kind: KindString, MaxLen: 128},
		{Key: "password", File: "main", Prop: "password",
			Label: "Пароль для входа", Section: SectionGeneral,
			Kind: KindString, MaxLen: 128, Secret: true, Clearable: true},
		{Key: "password_admin", File: "main", Prop: "passwordAdmin",
			Label: "Пароль администратора", Section: SectionAdmin,
			Kind: KindString, MaxLen: 128, Secret: true},
		{Key: "max_players", File: "main", Prop: "maxPlayers", Slots: true,
			Label: "Мест на сервере", Section: SectionGeneral,
			Kind: KindInt, Min: AtLeast(1), Max: AtMost(127)},
		{Key: "verify_signatures", File: "main", Prop: "verifySignatures",
			Label: "Проверять подписи модов", Section: SectionPlayers,
			Kind: KindEnum, Default: "2", Options: []Option{
				{Value: "0", Label: "Не проверять"},
				{Value: "2", Label: "Проверять"},
			}},
		{Key: "force_same_build", File: "main", Prop: "forceSameBuild",
			Label: "Требовать ту же версию игры", Section: SectionPlayers,
			Kind: KindBool, True: "1", False: "0", Default: "true"},
		{Key: "disable_von", File: "main", Prop: "disableVoN",
			Label: "Отключить голосовой чат", Section: SectionPlayers,
			Kind: KindBool, True: "1", False: "0"},
		{Key: "von_quality", File: "main", Prop: "vonCodecQuality",
			Label: "Качество голоса", Section: SectionPlayers,
			Kind: KindInt, Min: AtLeast(0), Max: AtMost(30), Default: "20"},
		{Key: "disable_third_person", File: "main", Prop: "disable3rdPerson",
			Label: "Только вид от первого лица", Section: SectionGameplay,
			Kind: KindBool, True: "1", False: "0"},
		{Key: "disable_crosshair", File: "main", Prop: "disableCrosshair",
			Label: "Убрать прицел", Section: SectionGameplay,
			Kind: KindBool, True: "1", False: "0"},
		{Key: "server_time", File: "main", Prop: "serverTime",
			Label: "Время в мире", Section: SectionWorld,
			Kind: KindString, MaxLen: 32, Default: "SystemTime",
			Hint: "SystemTime — время сервера, либо дата вида 2026/1/1/12/0"},
		{Key: "time_acceleration", File: "main", Prop: "serverTimeAcceleration",
			Label: "Ускорение дня", Section: SectionWorld,
			Kind: KindFloat, Min: AtLeast(0.1), Max: AtMost(64), Default: "1"},
		{Key: "night_acceleration", File: "main", Prop: "serverNightTimeAcceleration",
			Label: "Ускорение ночи", Section: SectionWorld,
			Kind: KindFloat, Min: AtLeast(0.1), Max: AtMost(64), Default: "1"},
		{Key: "time_persistent", File: "main", Prop: "serverTimePersistent",
			Label: "Сохранять время между перезапусками", Section: SectionWorld,
			Kind: KindBool, True: "1", False: "0"},
	}

	for _, key := range []string{"dayz", "dayzdev"} {
		register(Profile{
			Key: key,
			Files: []ConfigFile{
				{ID: "main", Path: "serverDZ.cfg", Format: FormatProperties, Title: "serverDZ.cfg"},
				{ID: "startup", Path: StartupPath, Format: FormatArgs, Title: "Параметры запуска"},
			},
			Note:   "Блоки class в serverDZ.cfg панель не трогает — правьте их во вкладке «Конфиг».",
			Fields: dayzFields,
		})
	}

	register(Profile{
		Key: "soulmask",
		Files: []ConfigFile{
			{ID: "startup", Path: StartupPath, Format: FormatArgs, Title: "Параметры запуска"},
			{ID: "game", Path: "WS/Saved/GameXishu.json", Format: FormatJSON,
				Title: "GameXishu.json", RawOnly: true},
		},
		Note: "Основные настройки Soulmask задаются аргументами запуска; тонкая настройка правил — в GameXishu.json.",
		Fields: []Field{
			{Key: "server_name", File: "startup", Prop: "SteamServerName",
				Label: "Название сервера", Section: SectionGeneral, Kind: KindString, MaxLen: 128},
			{Key: "max_players", File: "startup", Prop: "MaxPlayers", Slots: true,
				Label: "Мест на сервере", Section: SectionGeneral,
				Kind: KindInt, Min: AtLeast(1), Max: AtMost(70)},
			{Key: "password", File: "startup", Prop: "PSW",
				Label: "Пароль для входа", Section: SectionGeneral,
				Kind: KindString, MaxLen: 128, Secret: true, Clearable: true},
			{Key: "admin_password", File: "startup", Prop: "adminpsw",
				Label: "Пароль администратора", Section: SectionAdmin,
				Kind: KindString, MaxLen: 128, Secret: true},
			{Key: "save_interval", File: "startup", Prop: "saving",
				Label: "Интервал автосохранения, с", Section: SectionSaves,
				Kind: KindInt, Min: AtLeast(60), Max: AtMost(86400), Default: "600"},
			{Key: "backup_interval", File: "startup", Prop: "backup",
				Label: "Интервал копий, с", Section: SectionSaves,
				Kind: KindInt, Min: AtLeast(60), Max: AtMost(604800), Default: "1800"},
		},
	})
}
