package gamesettings

// Профили Minecraft.
//
// Java и Bedrock — разные профили, хотя файл у обоих называется
// server.properties. Раньше их склеивали по протоколу опроса, и Bedrock получал
// набор ключей от Java: `motd`, `pvp`, `enable-rcon`. Ни одного из них в Bedrock
// нет, RCON у него отсутствует как таковой, а имя сервера задаётся ключом
// `server-name`. Половина формы для Bedrock просто ничего не делала.
//
// Пять сборок Java (vanilla, Paper, Spigot, Forge, Fabric) отличаются
// загрузчиком, а не форматом настроек, поэтому у них один профиль.

func init() {
	register(Profile{
		Key:      "mcjava",
		SharedBy: []string{"mcpaper", "mcspigot", "mcforge", "mcfabric"},
		Files: []ConfigFile{
			{
				ID: "main", Path: "server.properties", Format: FormatProperties,
				Title:    "server.properties",
				Template: "#Minecraft server properties\n",
			},
			{ID: "ops", Path: "ops.json", Format: FormatJSON, Title: "ops.json", RawOnly: true},
			{ID: "whitelist", Path: "whitelist.json", Format: FormatJSON, Title: "whitelist.json", RawOnly: true},
			{ID: "startup", Path: StartupPath, Format: FormatArgs, Title: "Параметры запуска"},
		},
		Fields: []Field{
			{Key: "motd", File: "main", Prop: "motd",
				Label: "Описание в списке серверов", Section: SectionGeneral,
				Kind: KindString, MaxLen: 255, Clearable: true},
			{Key: "max_players", File: "main", Prop: "max-players", Slots: true,
				Label: "Мест на сервере", Section: SectionGeneral,
				Kind: KindInt, Min: AtLeast(1), Max: AtMost(5000)},
			{Key: "online_mode", File: "main", Prop: "online-mode",
				Label: "Проверять лицензию", Section: SectionPlayers,
				Kind: KindBool, Default: "true",
				Hint: "Выключение пускает нелицензионных клиентов и снимает защиту имён"},
			{Key: "white_list", File: "main", Prop: "white-list",
				Label: "Белый список", Section: SectionPlayers, Kind: KindBool},
			{Key: "enforce_whitelist", File: "main", Prop: "enforce-whitelist",
				Label: "Выгонять не из белого списка", Section: SectionPlayers, Kind: KindBool},
			{Key: "player_idle_timeout", File: "main", Prop: "player-idle-timeout",
				Label: "Кик за бездействие, мин", Section: SectionPlayers,
				Kind: KindInt, Min: AtLeast(0), Max: AtMost(999999), Default: "0",
				Hint: "0 — не выгонять"},
			{Key: "op_permission_level", File: "main", Prop: "op-permission-level",
				Label: "Уровень прав оператора", Section: SectionAdmin,
				Kind: KindEnum, Default: "4", Options: []Option{
					{Value: "1", Label: "1 — обход спавн-защиты"},
					{Value: "2", Label: "2 — командные блоки и читы"},
					{Value: "3", Label: "3 — кик и бан игроков"},
					{Value: "4", Label: "4 — все команды"},
				}},

			{Key: "gamemode", File: "main", Prop: "gamemode",
				Label: "Режим игры", Section: SectionGameplay, Kind: KindEnum, Default: "survival",
				Options: []Option{
					{Value: "survival", Label: "Выживание"},
					{Value: "creative", Label: "Творческий"},
					{Value: "adventure", Label: "Приключение"},
					{Value: "spectator", Label: "Наблюдатель"},
				}},
			{Key: "force_gamemode", File: "main", Prop: "force-gamemode",
				Label: "Возвращать режим при входе", Section: SectionGameplay, Kind: KindBool},
			{Key: "difficulty", File: "main", Prop: "difficulty",
				Label: "Сложность", Section: SectionGameplay, Kind: KindEnum, Default: "easy",
				AppliesLive: true,
				Options: []Option{
					{Value: "peaceful", Label: "Мирная"},
					{Value: "easy", Label: "Лёгкая"},
					{Value: "normal", Label: "Обычная"},
					{Value: "hard", Label: "Сложная"},
				}},
			{Key: "hardcore", File: "main", Prop: "hardcore",
				Label: "Хардкор", Section: SectionGameplay, Kind: KindBool,
				Hint: "Смерть окончательна, режим меняется на наблюдателя"},
			{Key: "pvp", File: "main", Prop: "pvp",
				Label: "Бой между игроками", Section: SectionGameplay, Kind: KindBool, Default: "true"},
			{Key: "allow_flight", File: "main", Prop: "allow-flight",
				Label: "Разрешить полёт", Section: SectionGameplay, Kind: KindBool},
			{Key: "allow_nether", File: "main", Prop: "allow-nether",
				Label: "Разрешить Нижний мир", Section: SectionGameplay, Kind: KindBool, Default: "true"},
			{Key: "enable_command_block", File: "main", Prop: "enable-command-block",
				Label: "Командные блоки", Section: SectionGameplay, Kind: KindBool},

			{Key: "level_name", File: "main", Prop: "level-name",
				Label: "Имя мира", Section: SectionWorld, Kind: KindString, MaxLen: 64,
				Hint: "Смена имени открывает другой мир, а не переименовывает текущий"},
			{Key: "level_seed", File: "main", Prop: "level-seed",
				Label: "Зерно генерации", Section: SectionWorld,
				Kind: KindString, MaxLen: 128, Clearable: true,
				Hint: "Действует только при создании нового мира"},
			{Key: "spawn_protection", File: "main", Prop: "spawn-protection",
				Label: "Радиус защиты спавна", Section: SectionWorld,
				Kind: KindInt, Min: AtLeast(0), Max: AtMost(999999)},
			{Key: "max_world_size", File: "main", Prop: "max-world-size",
				Label: "Радиус мира, блоков", Section: SectionWorld,
				Kind: KindInt, Min: AtLeast(1), Max: AtMost(29999984)},

			{Key: "view_distance", File: "main", Prop: "view-distance",
				Label: "Дальность прорисовки", Section: SectionPerformance,
				Kind: KindInt, Min: AtLeast(2), Max: AtMost(64), Default: "10",
				Hint: "Главный расход памяти и процессора"},
			{Key: "simulation_distance", File: "main", Prop: "simulation-distance",
				Label: "Дальность симуляции", Section: SectionPerformance,
				Kind: KindInt, Min: AtLeast(2), Max: AtMost(64), Default: "10"},
			{Key: "max_tick_time", File: "main", Prop: "max-tick-time",
				Label: "Предел такта, мс", Section: SectionPerformance,
				Kind: KindInt, Min: AtLeast(-1), Max: AtMost(2147483647),
				Hint: "-1 отключает сторожевой таймер"},
			{Key: "network_compression_threshold", File: "main", Prop: "network-compression-threshold",
				Label: "Порог сжатия пакетов", Section: SectionPerformance,
				Kind: KindInt, Min: AtLeast(-1), Max: AtMost(1048576)},

			{Key: "enable_status", File: "main", Prop: "enable-status",
				Label: "Отвечать в списке серверов", Section: SectionNetwork,
				Kind: KindBool, Default: "true"},
			{Key: "enable_query", File: "main", Prop: "enable-query",
				Label: "Протокол опроса", Section: SectionNetwork, Kind: KindBool},
			{Key: "query_port", File: "main", Prop: "query.port",
				Label: "Порт опроса", Section: SectionNetwork,
				Kind: KindInt, Min: AtLeast(1), Max: AtMost(65535), ReadOnly: true},
			{Key: "enable_rcon", File: "main", Prop: "enable-rcon",
				Label: "Удалённое управление", Section: SectionAdmin, Kind: KindBool,
				Hint: "Нужно для консоли в панели"},
			{Key: "rcon_password", File: "main", Prop: "rcon.password",
				Label: "Пароль RCON", Section: SectionAdmin,
				Kind: KindString, MaxLen: 128, Secret: true, Clearable: true},
			{Key: "rcon_port", File: "main", Prop: "rcon.port",
				Label: "Порт RCON", Section: SectionAdmin,
				Kind: KindInt, Min: AtLeast(1), Max: AtMost(65535), ReadOnly: true},
		},
	})

	register(Profile{
		Key: "mcbedrock",
		Files: []ConfigFile{
			{ID: "main", Path: "server.properties", Format: FormatProperties, Title: "server.properties"},
			{ID: "allowlist", Path: "allowlist.json", Format: FormatJSON, Title: "allowlist.json", RawOnly: true},
			{ID: "permissions", Path: "permissions.json", Format: FormatJSON, Title: "permissions.json", RawOnly: true},
			{ID: "startup", Path: StartupPath, Format: FormatArgs, Title: "Параметры запуска"},
		},
		Note: "У Bedrock нет удалённого управления по RCON — консоль работает через вывод сервера.",
		Fields: []Field{
			{Key: "server_name", File: "main", Prop: "server-name",
				Label: "Название сервера", Section: SectionGeneral, Kind: KindString, MaxLen: 255},
			{Key: "max_players", File: "main", Prop: "max-players", Slots: true,
				Label: "Мест на сервере", Section: SectionGeneral,
				Kind: KindInt, Min: AtLeast(1), Max: AtMost(100)},
			{Key: "online_mode", File: "main", Prop: "online-mode",
				Label: "Проверять учётную запись Xbox", Section: SectionPlayers,
				Kind: KindBool, Default: "true"},
			{Key: "allow_list", File: "main", Prop: "allow-list",
				Label: "Белый список", Section: SectionPlayers, Kind: KindBool},
			{Key: "default_player_permission_level", File: "main", Prop: "default-player-permission-level",
				Label: "Права нового игрока", Section: SectionPlayers, Kind: KindEnum, Default: "member",
				Options: []Option{
					{Value: "visitor", Label: "Гость"},
					{Value: "member", Label: "Участник"},
					{Value: "operator", Label: "Оператор"},
				}},
			{Key: "player_idle_timeout", File: "main", Prop: "player-idle-timeout",
				Label: "Кик за бездействие, мин", Section: SectionPlayers,
				Kind: KindInt, Min: AtLeast(0), Max: AtMost(999999), Default: "30"},

			{Key: "gamemode", File: "main", Prop: "gamemode",
				Label: "Режим игры", Section: SectionGameplay, Kind: KindEnum, Default: "survival",
				Options: []Option{
					{Value: "survival", Label: "Выживание"},
					{Value: "creative", Label: "Творческий"},
					{Value: "adventure", Label: "Приключение"},
				}},
			{Key: "difficulty", File: "main", Prop: "difficulty",
				Label: "Сложность", Section: SectionGameplay, Kind: KindEnum, Default: "easy",
				Options: []Option{
					{Value: "peaceful", Label: "Мирная"},
					{Value: "easy", Label: "Лёгкая"},
					{Value: "normal", Label: "Обычная"},
					{Value: "hard", Label: "Сложная"},
				}},
			{Key: "allow_cheats", File: "main", Prop: "allow-cheats",
				Label: "Разрешить читы", Section: SectionGameplay, Kind: KindBool},

			{Key: "level_name", File: "main", Prop: "level-name",
				Label: "Имя мира", Section: SectionWorld, Kind: KindString, MaxLen: 64},
			{Key: "level_seed", File: "main", Prop: "level-seed",
				Label: "Зерно генерации", Section: SectionWorld,
				Kind: KindString, MaxLen: 128, Clearable: true},

			{Key: "view_distance", File: "main", Prop: "view-distance",
				Label: "Дальность прорисовки", Section: SectionPerformance,
				Kind: KindInt, Min: AtLeast(4), Max: AtMost(64), Default: "32"},
			{Key: "tick_distance", File: "main", Prop: "tick-distance",
				Label: "Дальность симуляции", Section: SectionPerformance,
				Kind: KindInt, Min: AtLeast(4), Max: AtMost(12), Default: "4"},
			{Key: "max_threads", File: "main", Prop: "max-threads",
				Label: "Потоков обработки", Section: SectionPerformance,
				Kind: KindInt, Min: AtLeast(0), Max: AtMost(16), Default: "8",
				Hint: "0 — использовать все доступные"},
			{Key: "compression_threshold", File: "main", Prop: "compression-threshold",
				Label: "Порог сжатия пакетов", Section: SectionPerformance,
				Kind: KindInt, Min: AtLeast(0), Max: AtMost(65535), Default: "1"},
			{Key: "texturepack_required", File: "main", Prop: "texturepack-required",
				Label: "Требовать набор текстур", Section: SectionAdvanced, Kind: KindBool},
			{Key: "server_port", File: "main", Prop: "server-port",
				Label: "Игровой порт", Section: SectionNetwork,
				Kind: KindInt, Min: AtLeast(1), Max: AtMost(65535), ReadOnly: true,
				Hint: "Назначается панелью и перезаписывается при запуске"},
		},
	})
}
