package gamesettings

// Профили выживания и песочниц: Rust, Valheim, 7 Days to Die, Project Zomboid,
// Palworld, Unturned, Factorio.

func init() {
	// Rust настраивается переменными окружения, которые образ превращает в
	// аргументы запуска.
	register(Profile{
		Key: "rust",
		Files: []ConfigFile{
			{ID: "main", Path: "rust.env", Format: FormatEnv, Title: "rust.env"},
			{ID: "startup", Path: StartupPath, Format: FormatArgs, Title: "Параметры запуска"},
		},
		Fields: []Field{
			{Key: "hostname", File: "main", Prop: "RUST_HOSTNAME",
				Label: "Название сервера", Section: SectionGeneral, Kind: KindString, MaxLen: 128},
			{Key: "maxplayers", File: "main", Prop: "RUST_MAXPLAYERS", Slots: true,
				Label: "Мест на сервере", Section: SectionGeneral,
				Kind: KindInt, Min: AtLeast(1), Max: AtMost(500)},
			{Key: "identity", File: "main", Prop: "RUST_IDENTITY",
				Label: "Идентификатор сохранения", Section: SectionWorld,
				Kind: KindString, MaxLen: 64,
				Hint: "Смена открывает другой мир, а не переносит текущий"},
			{Key: "level", File: "main", Prop: "RUST_LEVEL",
				Label: "Карта", Section: SectionWorld, Kind: KindString, MaxLen: 128,
				Default: "Procedural Map"},
			{Key: "world_size", File: "main", Prop: "RUST_WORLD_SIZE",
				Label: "Размер мира", Section: SectionWorld,
				Kind: KindInt, Min: AtLeast(1000), Max: AtMost(6000), Default: "3000",
				Hint: "Больше размер — заметно дольше генерация и больше памяти"},
			{Key: "seed", File: "main", Prop: "RUST_SEED",
				Label: "Зерно генерации", Section: SectionWorld,
				Kind: KindInt, Min: AtLeast(0), Max: AtMost(2147483647)},
			{Key: "rcon_password", File: "main", Prop: "RUST_RCON_PASSWORD",
				Label: "Пароль RCON", Section: SectionAdmin,
				Kind: KindString, MaxLen: 128, Secret: true},
		},
	})

	// У Valheim файла настроек нет вовсе: всё живёт в аргументах запуска.
	register(Profile{
		Key: "valheim",
		Files: []ConfigFile{
			{ID: "startup", Path: StartupPath, Format: FormatArgs, Title: "Параметры запуска"},
		},
		Note: "Valheim настраивается только аргументами запуска — отдельного файла конфигурации у него нет.",
		Fields: []Field{
			{Key: "name", File: "startup", Prop: "name",
				Label: "Название сервера", Section: SectionGeneral, Kind: KindString, MaxLen: 120},
			{Key: "password", File: "startup", Prop: "password",
				Label: "Пароль для входа", Section: SectionGeneral,
				Kind: KindString, MaxLen: 120, Secret: true, Clearable: true,
				Hint: "Не менее пяти символов и не должен совпадать с именем мира"},
			{Key: "public", File: "startup", Prop: "public",
				Label: "Показывать в общем списке", Section: SectionNetwork,
				Kind: KindBool, True: "1", False: "0", Default: "1"},
			{Key: "world", File: "startup", Prop: "world",
				Label: "Имя мира", Section: SectionWorld, Kind: KindString, MaxLen: 120,
				Hint: "Смена имени открывает другой мир, а не переименовывает текущий"},
			{Key: "preset", File: "startup", Prop: "preset",
				Label: "Набор правил", Section: SectionGameplay, Kind: KindEnum,
				Options: []Option{
					{Value: "normal", Label: "Обычный"},
					{Value: "casual", Label: "Спокойный"},
					{Value: "easy", Label: "Лёгкий"},
					{Value: "hard", Label: "Тяжёлый"},
					{Value: "hardcore", Label: "Хардкор"},
					{Value: "immersive", Label: "Погружение"},
					{Value: "hammer", Label: "Строительство"},
				}},
			{Key: "saveinterval", File: "startup", Prop: "saveinterval",
				Label: "Интервал автосохранения, с", Section: SectionSaves,
				Kind: KindInt, Min: AtLeast(60), Max: AtMost(86400), Default: "1800"},
			{Key: "backups", File: "startup", Prop: "backups",
				Label: "Число копий мира", Section: SectionSaves,
				Kind: KindInt, Min: AtLeast(1), Max: AtMost(100), Default: "4"},
			{Key: "backupshort", File: "startup", Prop: "backupshort",
				Label: "Частая копия, с", Section: SectionSaves,
				Kind: KindInt, Min: AtLeast(60), Max: AtMost(86400)},
			{Key: "backuplong", File: "startup", Prop: "backuplong",
				Label: "Редкая копия, с", Section: SectionSaves,
				Kind: KindInt, Min: AtLeast(60), Max: AtMost(604800)},
		},
	})

	register(Profile{
		Key: "7d2d",
		Files: []ConfigFile{
			{ID: "main", Path: "serverconfig.xml", Format: FormatXMLProps, Title: "serverconfig.xml"},
			{ID: "startup", Path: StartupPath, Format: FormatArgs, Title: "Параметры запуска"},
		},
		Fields: []Field{
			{Key: "server_name", File: "main", Prop: "ServerName",
				Label: "Название сервера", Section: SectionGeneral, Kind: KindString, MaxLen: 120},
			{Key: "server_description", File: "main", Prop: "ServerDescription",
				Label: "Описание", Section: SectionGeneral,
				Kind: KindText, MaxLen: 300, Clearable: true},
			{Key: "server_password", File: "main", Prop: "ServerPassword",
				Label: "Пароль для входа", Section: SectionGeneral,
				Kind: KindString, MaxLen: 120, Secret: true, Clearable: true},
			{Key: "server_max_player_count", File: "main", Prop: "ServerMaxPlayerCount", Slots: true,
				Label: "Мест на сервере", Section: SectionGeneral,
				Kind: KindInt, Min: AtLeast(1), Max: AtMost(200)},
			{Key: "server_visibility", File: "main", Prop: "ServerVisibility",
				Label: "Видимость", Section: SectionNetwork, Kind: KindEnum, Default: "2",
				Options: []Option{
					{Value: "0", Label: "Скрытый"},
					{Value: "1", Label: "Только для друзей"},
					{Value: "2", Label: "Публичный"},
				}},
			{Key: "game_world", File: "main", Prop: "GameWorld",
				Label: "Мир", Section: SectionWorld, Kind: KindString, MaxLen: 120,
				Default: "Navezgane",
				Hint:    "Navezgane — готовая карта, RWG — случайная генерация"},
			{Key: "game_name", File: "main", Prop: "GameName",
				Label: "Имя сохранения", Section: SectionWorld, Kind: KindString, MaxLen: 120},
			{Key: "world_gen_seed", File: "main", Prop: "WorldGenSeed",
				Label: "Зерно генерации", Section: SectionWorld,
				Kind: KindString, MaxLen: 120, Clearable: true},
			{Key: "world_gen_size", File: "main", Prop: "WorldGenSize",
				Label: "Размер мира", Section: SectionWorld,
				Kind: KindInt, Min: AtLeast(1024), Max: AtMost(16384), Default: "6144"},
			{Key: "telnet_enabled", File: "main", Prop: "TelnetEnabled",
				Label: "Управление по Telnet", Section: SectionAdmin, Kind: KindBool},
			{Key: "control_panel_enabled", File: "main", Prop: "ControlPanelEnabled",
				Label: "Встроенная веб-панель", Section: SectionAdmin, Kind: KindBool},
		},
	})

	// Имя ini-файла Project Zomboid зависит от аргумента -servername, поэтому
	// путь собирается подстановкой.
	register(Profile{
		Key: "pzomboid",
		Files: []ConfigFile{
			{ID: "main", Path: "Zomboid/Server/{servername}.ini", Format: FormatINI, Title: "Настройки сервера"},
			{ID: "startup", Path: StartupPath, Format: FormatArgs, Title: "Параметры запуска"},
		},
		Fields: []Field{
			{Key: "servername", File: "startup", Prop: "servername",
				Label: "Имя набора настроек", Section: SectionAdvanced,
				Kind: KindString, MaxLen: 64, Default: "servertest",
				Hint: "Определяет имя файла настроек; менять без нужды не стоит"},
			{Key: "public_name", File: "main", Prop: "PublicName",
				Label: "Название сервера", Section: SectionGeneral, Kind: KindString, MaxLen: 120},
			{Key: "public_description", File: "main", Prop: "PublicDescription",
				Label: "Описание", Section: SectionGeneral,
				Kind: KindText, MaxLen: 500, Clearable: true},
			{Key: "password", File: "main", Prop: "Password",
				Label: "Пароль для входа", Section: SectionGeneral,
				Kind: KindString, MaxLen: 120, Secret: true, Clearable: true},
			{Key: "max_players", File: "main", Prop: "MaxPlayers", Slots: true,
				Label: "Мест на сервере", Section: SectionGeneral,
				Kind: KindInt, Min: AtLeast(1), Max: AtMost(100)},
			{Key: "public", File: "main", Prop: "Public",
				Label: "Показывать в общем списке", Section: SectionNetwork, Kind: KindBool},
			{Key: "open", File: "main", Prop: "Open",
				Label: "Открытый вход", Section: SectionPlayers, Kind: KindBool, Default: "true"},
			{Key: "pvp", File: "main", Prop: "PVP",
				Label: "Бой между игроками", Section: SectionGameplay, Kind: KindBool, Default: "true"},
			{Key: "global_chat", File: "main", Prop: "GlobalChat",
				Label: "Общий чат", Section: SectionGameplay, Kind: KindBool, Default: "true"},
			{Key: "welcome_message", File: "main", Prop: "ServerWelcomeMessage",
				Label: "Приветствие", Section: SectionGeneral,
				Kind: KindText, MaxLen: 500, Clearable: true},
			{Key: "reset_id", File: "main", Prop: "ResetID",
				Label: "Идентификатор сброса мира", Section: SectionWorld,
				Kind: KindString, MaxLen: 120,
				Hint: "Изменение заставит клиентов заново скачать мир"},
		},
	})

	register(Profile{
		Key: "palworld",
		Files: []ConfigFile{
			{ID: "main", Path: "Pal/Saved/Config/LinuxServer/PalWorldSettings.ini",
				Format: FormatUEOption, Title: "PalWorldSettings.ini"},
			{ID: "startup", Path: StartupPath, Format: FormatArgs, Title: "Параметры запуска"},
		},
		Fields: []Field{
			{Key: "server_name", File: "main", Prop: "ServerName",
				Label: "Название сервера", Section: SectionGeneral, Kind: KindString, MaxLen: 256},
			{Key: "server_description", File: "main", Prop: "ServerDescription",
				Label: "Описание", Section: SectionGeneral,
				Kind: KindText, MaxLen: 256, Clearable: true},
			{Key: "server_password", File: "main", Prop: "ServerPassword",
				Label: "Пароль для входа", Section: SectionGeneral,
				Kind: KindString, MaxLen: 120, Secret: true, Clearable: true},
			// Настоящий ключ числа мест — ServerPlayerMaxNum. Прежний реестр
			// считал слотовым полем MaxPlayers, которого в файле Palworld нет
			// вовсе: тариф дописывал в конфиг параметр, который игра не читает.
			{Key: "max_players", File: "main", Prop: "ServerPlayerMaxNum", Slots: true,
				Label: "Мест на сервере", Section: SectionGeneral,
				Kind: KindInt, Min: AtLeast(1), Max: AtMost(32)},
			{Key: "admin_password", File: "main", Prop: "AdminPassword",
				Label: "Пароль администратора", Section: SectionAdmin,
				Kind: KindString, MaxLen: 120, Secret: true},
			{Key: "use_auth", File: "main", Prop: "bUseAuth",
				Label: "Проверять учётные записи", Section: SectionPlayers,
				Kind: KindBool, True: "True", False: "False", Default: "true"},
			{Key: "pvp", File: "main", Prop: "bEnablePlayerToPlayerDamage",
				Label: "Бой между игроками", Section: SectionGameplay,
				Kind: KindBool, True: "True", False: "False"},
			{Key: "friendly_fire", File: "main", Prop: "bEnableFriendlyFire",
				Label: "Урон по своим", Section: SectionGameplay,
				Kind: KindBool, True: "True", False: "False"},
			{Key: "invader", File: "main", Prop: "bEnableInvaderEnemy",
				Label: "Набеги на базу", Section: SectionGameplay,
				Kind: KindBool, True: "True", False: "False", Default: "true"},
			{Key: "death_penalty", File: "main", Prop: "DeathPenalty",
				Label: "Потери при смерти", Section: SectionGameplay,
				Kind: KindEnum, Default: "All",
				Options: []Option{
					{Value: "None", Label: "Ничего не теряется"},
					{Value: "Item", Label: "Предметы из рюкзака"},
					{Value: "ItemAndEquipment", Label: "Предметы и снаряжение"},
					{Value: "All", Label: "Всё, включая палов"},
				}},
			{Key: "guild_max", File: "main", Prop: "GuildPlayerMaxNum",
				Label: "Игроков в гильдии", Section: SectionGameplay,
				Kind: KindInt, Min: AtLeast(1), Max: AtMost(100), Default: "20"},
			{Key: "exp_rate", File: "main", Prop: "ExpRate",
				Label: "Множитель опыта", Section: SectionRates,
				Kind: KindFloat, Min: AtLeast(0.1), Max: AtMost(20), Default: "1.000000"},
			{Key: "day_speed", File: "main", Prop: "DayTimeSpeedRate",
				Label: "Скорость дня", Section: SectionWorld,
				Kind: KindFloat, Min: AtLeast(0.1), Max: AtMost(5), Default: "1.000000"},
			{Key: "night_speed", File: "main", Prop: "NightTimeSpeedRate",
				Label: "Скорость ночи", Section: SectionWorld,
				Kind: KindFloat, Min: AtLeast(0.1), Max: AtMost(5), Default: "1.000000"},
		},
	})

	register(Profile{
		Key:      "unturned",
		SharedBy: []string{"untrm4", "untrm5"},
		Files: []ConfigFile{
			{ID: "main", Path: "Servers/server/Server/Commands.dat", Format: FormatKVSpace,
				Title: "Commands.dat"},
			{ID: "startup", Path: StartupPath, Format: FormatArgs, Title: "Параметры запуска"},
		},
		Note: "Commands.dat — список директив, которые сервер выполняет при запуске.",
		Fields: []Field{
			{Key: "server_name", File: "main", Prop: "Name",
				Label: "Название сервера", Section: SectionGeneral, Kind: KindString, MaxLen: 64},
			{Key: "max_players", File: "main", Prop: "MaxPlayers", Slots: true,
				Label: "Мест на сервере", Section: SectionGeneral,
				Kind: KindInt, Min: AtLeast(1), Max: AtMost(200)},
			{Key: "password", File: "main", Prop: "Password",
				Label: "Пароль для входа", Section: SectionGeneral,
				Kind: KindString, MaxLen: 64, Secret: true, Clearable: true},
			{Key: "login_token", File: "main", Prop: "LoginToken",
				Label: "Токен игрового сервера Steam", Section: SectionAdmin,
				Kind: KindString, MaxLen: 128, Secret: true, Clearable: true},
			{Key: "map", File: "main", Prop: "Map",
				Label: "Карта", Section: SectionWorld, Kind: KindString, MaxLen: 64,
				Default: "PEI"},
			{Key: "owner", File: "main", Prop: "Owner",
				Label: "Steam ID владельца", Section: SectionAdmin,
				Kind: KindString, MaxLen: 32, Clearable: true,
				Hint: "Даёт права администратора в игре"},
			{Key: "mode", File: "main", Prop: "Mode",
				Label: "Сложность", Section: SectionGameplay, Kind: KindEnum, Default: "Normal",
				Options: []Option{
					{Value: "Easy", Label: "Лёгкая"},
					{Value: "Normal", Label: "Обычная"},
					{Value: "Hard", Label: "Тяжёлая"},
				}},
			{Key: "perspective", File: "main", Prop: "Perspective",
				Label: "Вид от лица", Section: SectionGameplay, Kind: KindEnum, Default: "Both",
				Options: []Option{
					{Value: "First", Label: "Только от первого"},
					{Value: "Third", Label: "Только от третьего"},
					{Value: "Both", Label: "Любой"},
					{Value: "Vehicle", Label: "От третьего в транспорте"},
				}},
			{Key: "pvp", File: "main", Prop: "PvP",
				Label: "Бой между игроками", Section: SectionGameplay,
				Kind: KindBool, True: "1", False: "0"},
			{Key: "cheats", File: "main", Prop: "Cheats",
				Label: "Разрешить читы", Section: SectionGameplay,
				Kind: KindBool, True: "1", False: "0"},
		},
	})

	// Factorio читает настройки из JSON, путь к которому передаётся аргументом
	// --server-settings. Без него сервер стартует с настройками по умолчанию.
	register(Profile{
		Key: "factorio",
		Files: []ConfigFile{
			{ID: "main", Path: "server-settings.json", Format: FormatJSON, Title: "server-settings.json",
				Template: "{\n}\n"},
			{ID: "admins", Path: "server-adminlist.json", Format: FormatJSON,
				Title: "server-adminlist.json", RawOnly: true},
			{ID: "banlist", Path: "server-banlist.json", Format: FormatJSON,
				Title: "server-banlist.json", RawOnly: true},
			{ID: "startup", Path: StartupPath, Format: FormatArgs, Title: "Параметры запуска"},
		},
		Note: "Параметры запуска должны содержать --start-server с именем сохранения и --server-settings server-settings.json.",
		Fields: []Field{
			{Key: "name", File: "main", Prop: "name",
				Label: "Название сервера", Section: SectionGeneral, Kind: KindString, MaxLen: 128},
			{Key: "description", File: "main", Prop: "description",
				Label: "Описание", Section: SectionGeneral,
				Kind: KindText, MaxLen: 500, Clearable: true},
			{Key: "max_players", File: "main", Prop: "max_players", Slots: true,
				Label: "Мест на сервере", Section: SectionGeneral,
				Kind: KindInt, Min: AtLeast(0), Max: AtMost(500), Default: "0",
				Hint: "0 — без ограничения"},
			{Key: "game_password", File: "main", Prop: "game_password",
				Label: "Пароль для входа", Section: SectionGeneral,
				Kind: KindString, MaxLen: 128, Secret: true, Clearable: true},
			{Key: "public", File: "main", Prop: "visibility.public",
				Label: "Показывать в общем списке", Section: SectionNetwork, Kind: KindBool},
			{Key: "lan", File: "main", Prop: "visibility.lan",
				Label: "Видимость в локальной сети", Section: SectionNetwork,
				Kind: KindBool, Default: "true"},
			{Key: "username", File: "main", Prop: "username",
				Label: "Учётная запись factorio.com", Section: SectionAdmin,
				Kind: KindString, MaxLen: 128, Clearable: true,
				Hint: "Нужна только для публичного списка серверов"},
			{Key: "token", File: "main", Prop: "token",
				Label: "Токен factorio.com", Section: SectionAdmin,
				Kind: KindString, MaxLen: 128, Secret: true, Clearable: true},
			{Key: "require_user_verification", File: "main", Prop: "require_user_verification",
				Label: "Проверять учётные записи", Section: SectionPlayers,
				Kind: KindBool, Default: "true"},
			{Key: "afk_autokick_interval", File: "main", Prop: "afk_autokick_interval",
				Label: "Кик за бездействие, мин", Section: SectionPlayers,
				Kind: KindInt, Min: AtLeast(0), Max: AtMost(10000), Default: "0",
				Hint: "0 — не выгонять"},
			{Key: "allow_commands", File: "main", Prop: "allow_commands",
				Label: "Разрешить команды", Section: SectionGameplay,
				Kind: KindEnum, Default: "admins-only",
				Options: []Option{
					{Value: "true", Label: "Всем"},
					{Value: "false", Label: "Никому"},
					{Value: "admins-only", Label: "Только администраторам"},
				}},
			{Key: "auto_pause", File: "main", Prop: "auto_pause",
				Label: "Пауза без игроков", Section: SectionGameplay,
				Kind: KindBool, Default: "true"},
			{Key: "only_admins_can_pause_the_game", File: "main", Prop: "only_admins_can_pause_the_game",
				Label: "Ставить на паузу может только администратор", Section: SectionAdmin,
				Kind: KindBool, Default: "true"},
			{Key: "autosave_interval", File: "main", Prop: "autosave_interval",
				Label: "Интервал автосохранения, мин", Section: SectionSaves,
				Kind: KindInt, Min: AtLeast(1), Max: AtMost(1440), Default: "10"},
			{Key: "autosave_slots", File: "main", Prop: "autosave_slots",
				Label: "Число копий", Section: SectionSaves,
				Kind: KindInt, Min: AtLeast(1), Max: AtMost(50), Default: "5"},
			{Key: "non_blocking_saving", File: "main", Prop: "non_blocking_saving",
				Label: "Сохранять без остановки игры", Section: SectionPerformance,
				Kind: KindBool,
				Hint: "Требует примерно вдвое больше памяти"},
		},
	})
}
