WITH catalog(slug, repository, default_tag) AS (
    VALUES
        ('7d2d',         'vortanix/7d2d', 'latest'),
        ('7daystodie',   'vortanix/7d2d', 'latest'),
        ('7-days-to-die', 'vortanix/7d2d', 'latest'),
        ('seven_days_to_die', 'vortanix/7d2d', 'latest'),
        ('sevendaystodie', 'vortanix/7d2d', 'latest'),
        ('arksa',        'vortanix/arksa', 'latest'),
        ('ark-survival-ascended', 'vortanix/arksa', 'latest'),
        ('ark_survival_ascended', 'vortanix/arksa', 'latest'),
        ('ark_ascended', 'vortanix/arksa', 'latest'),
        ('asa',          'vortanix/arksa', 'latest'),
        ('arkse',        'vortanix/arkse', 'latest'),
        ('ark-survival-evolved', 'vortanix/arkse', 'latest'),
        ('ark_survival_evolved', 'vortanix/arkse', 'latest'),
        ('ark_evolved',  'vortanix/arkse', 'latest'),
        ('ark',          'vortanix/arkse', 'latest'),
        ('arma3',        'vortanix/arma3', 'latest'),
        ('arma-3',       'vortanix/arma3', 'latest'),
        ('arma_3',       'vortanix/arma3', 'latest'),
        ('armaref',      'vortanix/armaref', 'latest'),
        ('arma-reforger', 'vortanix/armaref', 'latest'),
        ('arma_reforger', 'vortanix/armaref', 'latest'),
        ('bbermuda',     'vortanix/bbermuda', 'latest'),
        ('beasts-of-bermuda', 'vortanix/bbermuda', 'latest'),
        ('beasts_of_bermuda', 'vortanix/bbermuda', 'latest'),
        ('conan',        'vortanix/conan', 'latest'),
        ('conan-exiles', 'vortanix/conan', 'latest'),
        ('conan_exiles', 'vortanix/conan', 'latest'),
        ('crmp',         'vortanix/crmp', 'latest'),
        ('gta_crmp',     'vortanix/crmp', 'latest'),
        ('cr-mp',        'vortanix/crmp', 'latest'),
        ('cr-mp0.3',     'vortanix/crmp', 'latest'),
        ('cs16',         'vortanix/cs16', 'latest'),
        ('cstrike',      'vortanix/cs16', 'latest'),
        ('counter-strike', 'vortanix/cs16', 'latest'),
        ('counter_strike', 'vortanix/cs16', 'latest'),
        ('cs_1_6',       'vortanix/cs16', 'latest'),
        ('cs2',          'vortanix/cs2', 'latest'),
        ('counter-strike2', 'vortanix/cs2', 'latest'),
        ('counter_strike2', 'vortanix/cs2', 'latest'),
        ('counter-strike_2', 'vortanix/cs2', 'latest'),
        ('counter_strike_2', 'vortanix/cs2', 'latest'),
        ('css',          'vortanix/css', 'latest'),
        ('cs:s',         'vortanix/css', 'latest'),
        ('cs_source',    'vortanix/css', 'latest'),
        ('counter-strike_source', 'vortanix/css', 'latest'),
        ('counter_strike_source', 'vortanix/css', 'latest'),
        ('daydrag',      'vortanix/daydrag', 'latest'),
        ('day-of-dragons', 'vortanix/daydrag', 'latest'),
        ('day_of_dragons', 'vortanix/daydrag', 'latest'),
        ('dayz',         'vortanix/dayz', 'latest'),
        ('dayz-standalone', 'vortanix/dayz', 'latest'),
        ('dayz_standalone', 'vortanix/dayz', 'latest'),
        ('dayzdev',      'vortanix/dayzdev', 'latest'),
        ('dayz-standalone-dev', 'vortanix/dayzdev', 'latest'),
        ('dayz_standalone_dev', 'vortanix/dayzdev', 'latest'),
        ('draconia',     'vortanix/draconia', 'latest'),
        ('draconia-online', 'vortanix/draconia', 'latest'),
        ('empyrion',     'vortanix/empyrion', 'latest'),
        ('empyrion-galactic-survival', 'vortanix/empyrion', 'latest'),
        ('empyrion_galactic_survival', 'vortanix/empyrion', 'latest'),
        ('enshroud',     'vortanix/enshroud', 'latest'),
        ('enshrouded',   'vortanix/enshroud', 'latest'),
        ('enshrouded-server', 'vortanix/enshroud', 'latest'),
        ('factorio',     'vortanix/factorio', 'latest'),
        ('factorio-server', 'vortanix/factorio', 'latest'),
        ('gmod',         'vortanix/gmod', 'latest'),
        ('garrysmod',    'vortanix/gmod', 'latest'),
        ('garrys_mod',   'vortanix/gmod', 'latest'),
        ('hytale',       'vortanix/hytale', 'latest'),
        ('hytale-server', 'vortanix/hytale', 'latest'),
        ('icarus',       'vortanix/icarus', 'latest'),
        ('icarus-survival', 'vortanix/icarus', 'latest'),
        ('isleevr',      'vortanix/isleevr', 'latest'),
        ('the-isle-evrima', 'vortanix/isleevr', 'latest'),
        ('the_isle_evrima', 'vortanix/isleevr', 'latest'),
        ('evrima',       'vortanix/isleevr', 'latest'),
        ('lifeyo',       'vortanix/lifeyo', 'latest'),
        ('life-is-feudal-your-own', 'vortanix/lifeyo', 'latest'),
        ('life_is_feudal_your_own', 'vortanix/lifeyo', 'latest'),
        ('mcbedrock',    'vortanix/mcbedrock', 'latest'),
        ('mcbedrk',      'vortanix/mcbedrock', 'latest'),
        ('bedrock',      'vortanix/mcbedrock', 'latest'),
        ('mcjava',       'vortanix/mcjava', 'latest'),
        ('mcpaper',      'vortanix/mcjava', 'latest'),
        ('mcspigot',     'vortanix/mcjava', 'latest'),
        ('mcforge',      'vortanix/mcjava', 'latest'),
        ('mcfabric',     'vortanix/mcjava', 'latest'),
        ('minecraft',    'vortanix/mcjava', 'latest'),
        ('mordhau',      'vortanix/mordhau', 'latest'),
        ('mta',          'vortanix/mta', 'latest'),
        ('mtasa',        'vortanix/mta', 'latest'),
        ('mta-sa',       'vortanix/mta', 'latest'),
        ('mta_sa',       'vortanix/mta', 'latest'),
        ('nosurv',       'vortanix/nosurv', 'latest'),
        ('no-one-survived', 'vortanix/nosurv', 'latest'),
        ('no_one_survived', 'vortanix/nosurv', 'latest'),
        ('palworld',     'vortanix/palworld', 'latest'),
        ('pal-world',    'vortanix/palworld', 'latest'),
        ('pathtit',      'vortanix/pathtit', 'latest'),
        ('path-of-titans', 'vortanix/pathtit', 'latest'),
        ('path_of_titans', 'vortanix/pathtit', 'latest'),
        ('pzomboid',     'vortanix/pzomboid', 'latest'),
        ('project-zomboid', 'vortanix/pzomboid', 'latest'),
        ('project_zomboid', 'vortanix/pzomboid', 'latest'),
        ('zomboid',      'vortanix/pzomboid', 'latest'),
        ('rs2vn',        'vortanix/rs2vn', 'latest'),
        ('rising-storm-2-vietnam', 'vortanix/rs2vn', 'latest'),
        ('rising_storm_2_vietnam', 'vortanix/rs2vn', 'latest'),
        ('rust',         'vortanix/rust', 'latest'),
        ('samp',         'vortanix/samp', '0.3.7-r3'),
        ('sa-mp',        'vortanix/samp', '0.3.7-r3'),
        ('samp03',       'vortanix/samp', '0.3.7-r3'),
        ('gta_samp',     'vortanix/samp', '0.3.7-r3'),
        ('satisfac',     'vortanix/satisfac', 'latest'),
        ('satisfactory', 'vortanix/satisfac', 'latest'),
        ('satisfactory-server', 'vortanix/satisfac', 'latest'),
        ('scum',         'vortanix/scum', 'latest'),
        ('sotf',         'vortanix/sotf', 'latest'),
        ('sons-of-the-forest', 'vortanix/sotf', 'latest'),
        ('sons_of_the_forest', 'vortanix/sotf', 'latest'),
        ('soulmask',     'vortanix/soulmask', 'latest'),
        ('spaceeng',     'vortanix/spaceeng', 'latest'),
        ('space-engineers', 'vortanix/spaceeng', 'latest'),
        ('space_engineers', 'vortanix/spaceeng', 'latest'),
        ('squad',        'vortanix/squad', 'latest'),
        ('starrupt',     'vortanix/starrupt', 'latest'),
        ('star-rupture', 'vortanix/starrupt', 'latest'),
        ('star_rupture', 'vortanix/starrupt', 'latest'),
        ('tf2',          'vortanix/tf2', 'latest'),
        ('teamfortress2', 'vortanix/tf2', 'latest'),
        ('team_fortress_2', 'vortanix/tf2', 'latest'),
        ('tf',           'vortanix/tf2', 'latest'),
        ('theisle',      'vortanix/theisle', 'latest'),
        ('the-isle',     'vortanix/theisle', 'latest'),
        ('the_isle',     'vortanix/theisle', 'latest'),
        ('ttworlds',     'vortanix/ttworlds', 'latest'),
        ('terratech-worlds', 'vortanix/ttworlds', 'latest'),
        ('terratech_worlds', 'vortanix/ttworlds', 'latest'),
        ('unturned',     'vortanix/unturned', 'latest'),
        ('unturn',       'vortanix/unturned', 'latest'),
        ('ut',           'vortanix/unturned', 'latest'),
        ('untrm4',       'vortanix/unturned', 'latest'),
        ('untrm5',       'vortanix/unturned', 'latest'),
        ('valheim',      'vortanix/valheim', 'latest'),
        ('valheim-server', 'vortanix/valheim', 'latest'),
        ('vrising',      'vortanix/vrising', 'latest'),
        ('v-rising',     'vortanix/vrising', 'latest'),
        ('v_rising',     'vortanix/vrising', 'latest')
),
desired AS (
    SELECT
        gv.id,
        c.repository || ':' || CASE
            WHEN split_part(gv.docker_image, ':', 1) = c.repository
                 AND NULLIF(split_part(gv.docker_image, ':', 2), '') IS NOT NULL
            THEN split_part(gv.docker_image, ':', 2)
            ELSE c.default_tag
        END AS image
    FROM core.game_versions gv
    JOIN core.games g ON g.id = gv.game_id AND g.tenant_id = gv.tenant_id
    JOIN catalog c ON c.slug = g.slug
    WHERE COALESCE(gv.docker_image, '') <> ''
)
UPDATE core.game_versions gv
SET docker_image = d.image
FROM desired d
WHERE gv.id = d.id
  AND gv.docker_image IS DISTINCT FROM d.image;
