package handlers

import (
	"github.com/go-chi/chi/v5"
)

func (h *Handler) mountProtected(r chi.Router) {
	r.Group(func(r chi.Router) {
		r.Use(h.authWithAPIKey)

		r.Use(h.tenantWriteRateLimit)
		r.Get("/v1/me", h.Me)
		r.Patch("/v1/me/password", h.ChangePassword)
		r.Post("/v1/auth/logout", h.Logout)

		r.Post("/v1/email/verification-notification", h.SendEmailVerification)
		r.Get("/v1/email/verify/{id}/{hash}", h.VerifyEmail)

		r.Get("/v1/account", h.GetAccount)
		r.Patch("/v1/account", h.UpdateAccount)
		r.Get("/v1/account/sessions", h.ListAccountSessions)
		r.Post("/v1/account/sessions/destroy", h.DestroySession)
		r.Post("/v1/account/avatar", h.UploadAvatar)
		r.Post("/v1/account/email/change", h.ChangeEmail)
		r.Post("/v1/account/2fa/generate", h.Generate2FA)
		r.Post("/v1/account/2fa/enable", h.Enable2FA)
		r.Post("/v1/account/2fa/disable", h.Disable2FA)
		r.Get("/v1/account/social/{provider}/redirect", h.SocialLinkRedirect)
		r.Post("/v1/account/social/{provider}/exchange", h.SocialLinkExchange)
		r.Post("/v1/account/social/{provider}/unlink", h.SocialUnlink)
		r.Get("/v1/account/telegram/link", h.TelegramLink)

		r.Get("/v1/dashboard", h.Dashboard)
		r.Get("/v1/my-servers", h.MyServers)
		r.Get("/v1/activity", h.ListActivity)
		r.Get("/v1/translations/messages", h.Translations)
		r.Post("/v1/locale/{locale}", h.SetLocale)

		r.Get("/v1/notifications", h.ListNotifications)
		r.Get("/v1/notifications/unread-count", h.NotificationsUnreadCount)
		r.Post("/v1/notifications/read-all", h.NotificationsReadAll)
		r.Post("/v1/notifications/{id}/read", h.NotificationRead)
		// Удаления не было вовсе: убрать запись с глаз можно было только
		// пометкой прочитанной, а лента росла вечно.
		r.Delete("/v1/notifications/read", h.NotificationsClearRead)
		r.Delete("/v1/notifications/{id}", h.NotificationDelete)

		r.Get("/v1/games", h.ListGamesPublic)
		r.Get("/v1/games/{slug}", h.GetGamePublic)
		r.Get("/v1/features", h.Features)
		r.Get("/v1/tariffs/public", h.ListTariffsPublic)

		r.Get("/v1/trial", h.TrialStatus)
		r.Post("/v1/trial", h.TrialCreate)

		r.Get("/v1/rent-server", h.RentServerForm)
		r.Post("/v1/rent-server", h.RentServerSubmit)

		r.Get("/v1/billing", h.GetBilling)
		r.Post("/v1/billing/wallets/create", h.CreateWallet)
		r.Get("/v1/billing/topup", h.TopupForm)
		r.Post("/v1/billing/topup/create", h.CreateTopup)
		r.Get("/v1/billing/payments/{id}", h.GetPayment)
		r.Get("/v1/billing/payments/{id}/receipt", h.PaymentReceipt)

		// База знаний стоит перед формой обращения: если ответ уже написан,
		// тикет не появится вовсе.
		r.Get("/v1/kb", h.ListKBArticles)
		r.Get("/v1/kb/{slug}", h.GetKBArticle)

		r.Get("/v1/support/create", h.SupportCreateForm)
		r.Get("/v1/support", h.ListSupportTickets)
		r.Post("/v1/support", h.CreateSupportTicket)
		r.Get("/v1/support/unread-count", h.SupportUnreadCount)
		r.Get("/v1/support/{id}", h.GetSupportTicket)
		r.Post("/v1/support/{id}/reply", h.ReplySupportTicket)
		r.Patch("/v1/support/{id}/notify", h.SetTicketNotify)
		r.Post("/v1/support/{id}/attachments", h.UploadSupportAttachment)
		r.Get("/v1/support/{id}/attachments/{messageId}", h.DownloadSupportAttachment)
		r.Post("/v1/support/{id}/close", h.CloseSupportTicket)

		r.Get("/v1/news", h.ListNews)
		r.Get("/v1/news/{slug}", h.GetNews)
		r.Post("/v1/news/read", h.MarkNewsRead)

		r.Get("/v1/monitoring", h.MonitoringIndex)
		r.Get("/v1/monitoring/top", h.MonitoringTop)
		r.Get("/v1/monitoring/{id}", h.MonitoringShow)
		r.Get("/v1/monitoring/{id}/stats", h.MonitoringServerStats)
		r.Get("/v1/monitoring/{id}/incidents", h.MonitoringIncidents)
		r.Get("/v1/monitoring/{id}/settings", h.MonitoringSettingsShow)
		r.Put("/v1/monitoring/{id}/settings", h.MonitoringSettingsUpdate)

		r.Get("/v1/daily-bonus", h.DailyBonusIndex)
		r.Post("/v1/daily-bonus/spin", h.DailyBonusSpin)

		r.Get("/v1/activity/export.csv", h.ExportActivityCSV)
		r.Get("/v1/notifications/channels", h.NotificationChannelsShow)
		r.Put("/v1/notifications/channels", h.NotificationChannelsUpdate)

		r.Get("/v1/hosting/my", h.MyHosting)
		r.Get("/v1/hosting/rent", h.HostingRentForm)
		r.Post("/v1/hosting/rent", h.HostingRentSubmit)
		r.Get("/v1/hosting/{id}", h.GetHostingAccount)
		r.Get("/v1/hosting/{id}/domains", h.ListHostingDomains)
		r.Post("/v1/hosting/{id}/domains", h.CreateHostingDomain)
		r.Get("/v1/hosting/{id}/databases", h.ListHostingDatabases)
		r.Post("/v1/hosting/{id}/databases", h.CreateHostingDatabase)
		r.Get("/v1/hosting/{id}/emails", h.ListHostingEmails)
		r.Post("/v1/hosting/{id}/emails", h.CreateHostingEmail)
		r.Post("/v1/hosting/{id}/renew", h.RenewHostingAccount)
		r.Post("/v1/hosting/{id}/change-password", h.ChangeHostingPassword)

		r.Route("/v1/users", func(r chi.Router) {
			r.Use(h.usersRBACMiddleware)
			r.Get("/", h.ListUsers)
			r.Get("/create", h.AdminUsersCreateForm)
			r.Post("/", h.CreateUser)
			r.Get("/{id}", h.GetUser)
			r.Get("/{id}/edit", h.AdminUserEditForm)
			r.Patch("/{id}", h.UpdateUser)
			r.Put("/{id}", h.UpdateUser)
			r.Delete("/{id}", h.DeleteUser)
			r.Post("/{id}/verify-email", h.VerifyUserEmail)
			r.Post("/{id}/toggle-block", h.ToggleUserBlock)
			r.Post("/{id}/impersonate", h.ImpersonateUser)
			r.Post("/{id}/wallets/create", h.AdminUserCreateWallet)
			r.Post("/{id}/balance", h.AdminAdjustUserBalance)
		})

		r.Route("/v1/servers", func(r chi.Router) {
			r.Get("/", h.ListServers)
			r.Post("/", h.CreateServer)
			r.Get("/{id}", h.GetServer)
			r.Get("/{id}/detail", h.GetServerDetail)
			r.Patch("/{id}", h.PatchServer)
			r.Delete("/{id}", h.DeleteServer)
			r.Post("/{id}/power", h.PowerServer)
			r.Post("/{id}/console-ticket", h.CreateConsoleTicket)
			r.Get("/{id}/metrics", h.GetServerMetrics)
			r.Get("/{id}/logs", h.GetServerLogs)
			r.Get("/{id}/install-log", h.ServerInstallLog)
			r.Get("/{id}/status", h.GetServerStatus)
			r.Post("/{id}/console-command", h.ServerConsoleCommand)
			r.Post("/{id}/maps-folder/list", h.ServerMapsFolderList)
			r.Post("/{id}/maps-folder/change", h.ServerMapChangeByName)
			r.Get("/{id}/plugins", h.ServerPluginsList)
			r.Post("/{id}/plugins/{pluginId}/install", h.ServerPluginInstall)
			r.Post("/{id}/plugins/{pluginId}/uninstall", h.ServerPluginUninstall)
			r.Post("/{id}/plugins/{pluginId}/toggle", h.ServerPluginToggle)
			r.Get("/{id}/maps", h.ServerMapsList)
			r.Post("/{id}/maps/{mapId}/install", h.ServerMapInstall)
			r.Post("/{id}/maps/{mapId}/uninstall", h.ServerMapUninstall)
			r.Post("/{id}/maps/{mapId}/activate", h.ServerMapActivate)
			r.Get("/{id}/mysql", h.ServerMysqlInfo)
			r.Post("/{id}/mysql/reset-password", h.ServerMysqlResetPassword)
			r.Post("/{id}/mysql/delete", h.ServerMysqlDelete)
			r.Post("/{id}/mysql/migrate", h.ServerMysqlMigrate)
			r.Post("/{id}/mysql/database/create", h.ServerMysqlCreateDatabase)
			r.Post("/{id}/mysql/database/delete", h.ServerMysqlDeleteDatabase)
			r.Post("/{id}/mysql/user/create", h.ServerMysqlCreateUser)
			r.Post("/{id}/mysql/user/delete", h.ServerMysqlDeleteUser)
			r.Post("/{id}/mysql/user/reset-password", h.ServerMysqlResetUserPassword)
			r.Post("/{id}/files/list", h.ServerFilesList)
			r.Post("/{id}/files/read", h.ServerFilesRead)
			r.Post("/{id}/files/write", h.ServerFilesWrite)
			r.Get("/{id}/files/download", h.ServerFilesDownload)
			r.Post("/{id}/cron/list", h.ServerCronList)
			r.Post("/{id}/cron/create", h.ServerCronCreate)
			r.Post("/{id}/cron/delete", h.ServerCronDelete)
			r.Post("/{id}/cron/toggle", h.ServerCronToggle)
			r.Post("/{id}/firewall/list", h.ServerFirewallList)
			r.Post("/{id}/firewall/create", h.ServerFirewallCreate)
			r.Post("/{id}/firewall/delete", h.ServerFirewallDelete)
			r.Post("/{id}/firewall/toggle", h.ServerFirewallToggle)
			r.Get("/{id}/friends", h.ServerFriendsList)
			r.Post("/{id}/friends/add", h.ServerFriendsAdd)
			r.Post("/{id}/friends/remove", h.ServerFriendsRemove)
			r.Post("/{id}/friends/update", h.ServerFriendsUpdate)
			r.Post("/{id}/backups", h.ServerBackupCreate)
			r.Get("/{id}/backups", h.ServerBackupList)
			r.Delete("/{id}/backups", h.ServerBackupDelete)
			r.Post("/{id}/backups/restore", h.ServerBackupRestore)
			r.Get("/{id}/backups/remote", h.ServerRemoteBackupList)
			r.Post("/{id}/backups/remote/restore", h.ServerRemoteBackupRestore)
			r.Post("/{id}/backups/remote/delete", h.ServerRemoteBackupDelete)
			r.Get("/{id}/backup-schedule", h.GetServerBackupSchedule)
			r.Put("/{id}/backup-schedule", h.PutServerBackupSchedule)
			r.Post("/{id}/update", h.UpdateServerGame)
			r.Post("/{id}/reinstall", h.ReinstallServer)
			r.Post("/{id}/version", h.ServerSwitchVersion)
			r.Post("/{id}/auto-start", h.ServerAutoStart)
			r.Post("/{id}/auto-renew", h.ServerAutoRenew)
			r.Post("/{id}/startup-params", h.ServerStartupParams)
			// Настройки: панель получает схему формы вместе со значениями и не
			// хранит список полей у себя.
			r.Get("/{id}/settings", h.ServerSettingsSchema)
			r.Post("/{id}/settings", h.ServerSettingsSave)
			r.Get("/{id}/settings/files/{fileId}", h.ServerSettingsFileGet)
			r.Put("/{id}/settings/files/{fileId}", h.ServerSettingsFilePut)
			r.Post("/{id}/renew/preview", h.ServerRenewPreview)
			r.Post("/{id}/renew", h.ServerRenew)
			r.Get("/{id}/tariffs", h.ServerTariffList)
			r.Post("/{id}/tariff/change/preview", h.ServerTariffChangePreview)
			r.Post("/{id}/tariff/change", h.ServerTariffChange)
			r.Post("/{id}/tariff/resources/preview", h.ServerTariffResourcesPreview)
			r.Post("/{id}/tariff/resources", h.ServerTariffResources)
			r.Post("/{id}/files/mkdir", h.ServerFilesMkdir)
			r.Post("/{id}/files/delete", h.ServerFilesDelete)
			r.Post("/{id}/files/upload", h.ServerFilesUpload)
			r.Get("/{id}/ftp", h.ServerFtpList)
			r.Post("/{id}/ftp", h.ServerFtpCreate)
			r.Post("/{id}/ftp/reset-password", h.ServerFtpResetPassword)
			r.Post("/{id}/ftp/delete", h.ServerFtpDelete)
			r.Post("/{id}/ports/list", h.ServerPortsList)
			r.Post("/{id}/ports/create", h.ServerPortsCreate)
			r.Post("/{id}/ports/delete", h.ServerPortsDelete)
		})

		r.Route("/v1/admin", func(r chi.Router) {
			r.Use(h.adminMiddleware)
			r.Use(h.adminRBACMiddleware)
			r.Get("/dashboard", h.AdminDashboard)
			r.Get("/dashboard/nodes", h.AdminDashboardNodes)
			r.Get("/dashboard/series", h.AdminDashboardSeries)
			r.Get("/analytics", h.AdminAnalytics)
			r.Get("/analytics/export.csv", h.AdminAnalyticsExport)
			r.Get("/servers/{id}/charges", h.AdminServerAnalytics)
			r.Get("/locations", h.ListAdminLocations)
			r.Post("/locations", h.CreateAdminLocation)
			r.Post("/locations/ssh/test", h.TestAdminLocationSSHBody)
			r.Get("/locations/{id}", h.GetAdminLocation)
			r.Get("/locations/{id}/edit", h.GetAdminLocationEdit)
			r.Get("/locations/{id}/install", h.GetAdminLocationInstallScript)
			r.Post("/locations/{id}/agent-token/regenerate", h.RegenerateAdminLocationAgentToken)
			r.Post("/locations/{id}/ssh/test", h.TestAdminLocationSSH)
			r.Put("/locations/{id}", h.PutAdminLocation)
			r.Patch("/locations/{id}", h.PatchAdminLocation)
			r.Patch("/locations/{id}/toggle", h.ToggleAdminLocation)
			r.Post("/locations/{id}/maintenance", h.SetNodeMaintenance)
			r.Post("/locations/{id}/bulk", h.AdminNodeBulkAction)
			r.Get("/locations/{id}/ips", h.AdminNodeIPList)
			r.Post("/locations/{id}/ips", h.AdminNodeIPAdd)
			r.Post("/locations/{id}/ips/import", h.AdminNodeIPImport)
			r.Delete("/locations/{id}/ips/{ipId}", h.AdminNodeIPDelete)
			r.Get("/locations/{id}/capacity", h.AdminNodeCapacity)
			r.Patch("/locations/{id}/capacity", h.AdminNodeCapacityUpdate)
			r.Delete("/locations/{id}", h.DeleteAdminLocation)
			r.Get("/locations/{id}/setup", h.GetAdminLocationSetup)
			r.Get("/locations/{id}/setup/status", h.GetAdminLocationSetupStatus)
			r.Post("/locations/{id}/setup/{step}", h.RunAdminLocationSetupStep)
			r.Post("/locations/{id}/pull-daemon", h.LocationPullDaemon)
			r.Get("/locations/{id}/daemon", h.GetAdminLocationDaemon)
			r.Post("/locations/{id}/daemon/refresh", h.RefreshAdminLocationDaemon)
			r.Post("/locations/{id}/daemon/restart", h.RestartAdminLocationDaemon)
			r.Post("/locations/{id}/daemon", h.InstallAdminLocationDaemon)
			r.Get("/daemons", h.ListAdminAgents)
			r.Get("/daemons/{id}", h.GetAdminAgentShow)
			r.Get("/daemons/{id}/logs", h.GetAdminAgentLogs)
			r.Get("/daemons/{id}/servers", h.GetAdminAgentServers)
			r.Post("/daemons/{id}/exec", h.PostAdminAgentExec)
			r.Post("/daemons/{id}/refresh", h.RefreshAdminLocationDaemon)
			r.Post("/daemons/{id}/restart", h.RestartAdminLocationDaemon)
			r.Post("/daemons/{id}/install", h.InstallAdminLocationDaemon)
			r.Get("/images", h.ListNodeImages)
			r.Post("/images", h.SetNodeImageTag)
			r.Post("/images/build-flag", h.SetImageBuildFlag)
			r.Post("/images/build", h.BuildNodeImages)
			r.Get("/jobs", h.AdminJobsList)
			r.Post("/jobs/retry-failed", h.AdminJobsRetryFailed)
			r.Post("/jobs/cleanup", h.AdminJobsCleanup)
			r.Post("/jobs/{id}/retry", h.AdminJobRetry)
			r.Post("/jobs/{id}/cancel", h.AdminJobCancel)
			r.Delete("/jobs/{id}", h.AdminJobDelete)
			r.Get("/updates", h.AdminUpdates)
			r.Get("/games", h.ListAdminGames)
			r.Post("/games", h.CreateAdminGame)
			r.Get("/games/{id}", h.GetAdminGame)
			r.Get("/games/{id}/edit", h.GetAdminGameEdit)
			r.Put("/games/{id}", h.UpdateAdminGame)
			r.Patch("/games/{id}", h.UpdateAdminGame)
			r.Delete("/games/{id}", h.DeleteAdminGame)
			r.Post("/games/{id}/toggle", h.AdminGameToggle)
			r.Route("/games/{gameId}/versions", func(r chi.Router) {
				r.Get("/", h.ListGameVersions)
				r.Post("/", h.CreateGameVersion)
				r.Patch("/{id}", h.UpdateGameVersion)
				r.Delete("/{id}", h.DeleteGameVersion)
			})
			r.Get("/tariffs/create", h.AdminTariffCreateForm)
			r.Get("/tariffs", h.ListTariffsAdmin)
			r.Post("/tariffs", h.CreateTariff)
			r.Get("/tariffs/{id}/edit", h.AdminTariffEditForm)
			r.Get("/tariffs/{id}", h.GetAdminTariff)
			r.Put("/tariffs/{id}", h.PutAdminTariff)
			r.Patch("/tariffs/{id}", h.UpdateTariff)
			r.Delete("/tariffs/{id}", h.DeleteTariff)
			r.Post("/tariffs/{id}/duplicate", h.AdminTariffDuplicate)
			r.Get("/plugins", h.ListPlugins)
			r.Post("/plugins", h.CreatePlugin)
			r.Post("/plugins/{id}/archive", h.UploadPluginArchive)
			r.Post("/plugins/{id}/image", h.UploadPluginImage)
			r.Delete("/plugins/{id}", h.DeletePlugin)
			r.Get("/maps", h.ListMaps)
			r.Post("/maps", h.CreateMap)
			r.Post("/maps/{id}/archive", h.UploadMapArchive)
			r.Delete("/maps/{id}", h.DeleteMap)
			r.Get("/billing", h.AdminBilling)
			r.Get("/billing/refund-support", h.AdminRefundSupport)
			r.Post("/billing/payments/{id}/refund", h.AdminRefundPayment)
			r.Get("/payment-providers", h.ListPaymentProviders)
			r.Patch("/payment-providers/{id}", h.UpdatePaymentProvider)
			r.Get("/news", h.ListNewsAdmin)
			r.Post("/news", h.CreateNews)
			r.Put("/news/{id}", h.UpdateNews)
			r.Patch("/news/{id}", h.UpdateNews)
			r.Post("/news/{id}/images", h.UploadNewsImage)
			r.Delete("/news/{id}/images/{imageId}", h.DeleteNewsImage)
			r.Delete("/news/{id}", h.DeleteNews)
			r.Get("/support", h.AdminSupportQueue)
			r.Patch("/support/{id}", h.AdminSupportUpdate)

			r.Get("/kb", h.AdminListKBArticles)
			r.Post("/kb", h.AdminSaveKBArticle)
			r.Delete("/kb/{id}", h.AdminDeleteKBArticle)
			r.Get("/settings", h.GetAdminSettings)
			r.Post("/settings", h.UpdateAdminSettings)
			r.Patch("/settings", h.UpdateAdminSettings)
			r.Post("/settings/test-mail", h.AdminSettingsTestMail)
			r.Post("/settings/test-telegram", h.AdminSettingsTestTelegram)
			r.Post("/settings/test-files-storage", h.AdminSettingsTestFilesStorage)
			r.Get("/settings/readiness", h.AdminCutoverReadiness)
			r.Get("/settings/appearance", h.GetAdminAppearance)
			r.Post("/settings/appearance", h.UpdateAdminAppearance)
			r.Get("/groups", h.GetGroups)
			r.Patch("/groups", h.UpdateGroups)
			r.Post("/groups", h.UpdateGroups)
			r.Get("/webhooks", h.AdminWebhooksList)
			r.Post("/webhooks", h.AdminWebhookCreate)
			r.Patch("/webhooks/{id}", h.AdminWebhookUpdate)
			r.Delete("/webhooks/{id}", h.AdminWebhookDelete)
			r.Get("/webhooks/{id}/deliveries", h.AdminWebhookDeliveries)
			r.Post("/webhooks/{id}/test", h.AdminWebhookTest)
			r.Get("/api-keys", h.AdminAPIKeysList)
			r.Post("/api-keys", h.AdminAPIKeyCreate)
			r.Delete("/api-keys/{id}", h.AdminAPIKeyRevoke)
			r.Get("/search", h.AdminSearch)
			r.Get("/security/logins", h.AdminLoginAttempts)
			r.Get("/security/ip-blocks", h.AdminIPBlocksList)
			r.Post("/security/ip-blocks", h.AdminIPBlockCreate)
			r.Delete("/security/ip-blocks/{id}", h.AdminIPBlockDelete)
			r.Get("/logs", h.AdminLogs)
			r.Get("/servers", h.AdminListServers)
			r.Post("/servers/{id}/toggle-block", h.AdminToggleServerBlock)
			r.Get("/servers/{id}/migration-targets", h.AdminServerMigrationTargets)
			r.Get("/servers/{id}/migrations", h.AdminServerMigrations)
			r.Post("/servers/{id}/migrate", h.AdminServerMigrate)
			r.Post("/servers/{id}/ip", h.AdminServerAssignIP)
			r.Post("/servers/{id}/ip/release", h.AdminServerReleaseIP)
			r.Get("/mysql", h.AdminMysqlIndex)
			r.Post("/mysql/instance/create", h.AdminMysqlInstanceCreate)
			r.Patch("/mysql/instance/update", h.AdminMysqlInstanceUpdate)
			r.Post("/mysql/instance/delete", h.AdminMysqlInstanceDelete)
			r.Get("/language", h.AdminLanguageList)
			r.Patch("/language", h.AdminLanguageUpdate)
			r.Get("/bug-report", h.AdminBugReportList)
			r.Post("/bug-report", h.AdminBugReportCreate)
			r.Get("/hosting/servers", h.AdminHostingServers)
			r.Post("/hosting/servers", h.CreateHostingServer)
			r.Get("/hosting/servers/{id}", h.GetHostingServer)
			r.Delete("/hosting/servers/{id}", h.DeleteHostingServer)
			r.Get("/hosting/plans", h.AdminHostingPlans)
			r.Post("/hosting/plans", h.CreateHostingPlan)
			r.Delete("/hosting/plans/{id}", h.DeleteHostingPlan)
			r.Get("/hosting/accounts", h.AdminHostingAccounts)
			r.Post("/hosting/accounts/{id}/suspend", h.AdminHostingAccountSuspend)
			r.Post("/hosting/accounts/{id}/unsuspend", h.AdminHostingAccountUnsuspend)
			r.Get("/promotions", h.ListPromotions)
			r.Post("/promotions", h.CreatePromotion)
			r.Patch("/promotions/{id}", h.UpdatePromotion)
			r.Delete("/promotions/{id}", h.DeletePromotion)
			r.Get("/mailings", h.ListMailings)
			r.Post("/mailings", h.CreateMailing)
			r.Post("/mailings/{id}/send", h.SendMailing)
			r.Delete("/mailings/{id}", h.DeleteMailing)
		})
	})
}

func (h *Handler) mountPublicMonitoring(r chi.Router) {
	r.Get("/v1/monitoring/public/top", h.MonitoringTop)
	r.Get("/v1/monitoring/public/{id}/live", h.MonitoringPublicLive)
	r.Post("/v1/monitoring/public/{id}/vote", h.MonitoringPublicVote)
	r.Get("/v1/monitoring/public/{id}/stats", h.MonitoringPublicStats)
	r.Get("/v1/monitoring/public/{id}/banner/{size}.png", h.MonitoringPublicBanner)
	r.Get("/v1/monitoring/public/{id}", h.MonitoringPublic)
}

func (h *Handler) mountPublicAuth(r chi.Router) {
	// Обновление сессии не может стоять за проверкой access-токена: тот живёт
	// час, и как только он истёк, обновиться становится нечем — 401 приходил
	// на сам /v1/auth/refresh. Продление работало только пока оно не нужно, а
	// после часа простоя пользователя выкидывало на вход при живом
	// refresh-токене. Свою аутентификацию хендлер делает сам: проверяет подпись
	// и срок refresh-токена, живость сессии в core.user_sessions и активность
	// пользователя, из claims не читая ничего. Базу арендатора выбирает общий
	// withTenantPool по X-Tenant-Slug — так же, как для /v1/auth/login.
	r.Post("/v1/auth/refresh", h.Refresh)
	r.Post("/v1/auth/forgot-password", h.ForgotPassword)
	r.Post("/v1/auth/reset-password", h.ResetPassword)
	r.Post("/v1/auth/2fa/challenge", h.Challenge2FA)
	r.Get("/v1/auth/social/providers", h.SocialProviders)
	r.Get("/v1/auth/social/{provider}/redirect", h.SocialRedirect)
	r.Post("/v1/auth/social/{provider}/exchange", h.SocialExchange)
	r.Get("/v1/auth/telegram/callback", h.TelegramCallback)
}
